### ISSUE TITLE
Prostheses are fucked for non standart body shapes

### ISSUE THREAD

**Issue by ghost** [discordia-space/CEV-Eris#1017]
![image](https://user-images.githubusercontent.com/20542000/31260710-8f318672-aa71-11e7-834b-d9ad097287ce.png)
![image](https://user-images.githubusercontent.com/20542000/31260712-91b49ab0-aa71-11e7-8216-5f8ea3e59281.png)

**Comment by ACCount12** [comment]
Non-standard body shapes are gone.
