### ISSUE TITLE
IHS access rework

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1090]
Redo the accesses of the IHS, giving the inspector and medical specialist the necessary access to the common arsenal and shooting range, but not giving them access to the closets of operatives. This can be done by adding additional access for operatives.

**Comment by hyperioo** [comment]
I think this issue can be closed. I did a test by claiming a locker with an IH operative ID and couldn't open it with captain's spare ID ("Access Denied"). I guess it was corrected since Nov 2017.
