### ISSUE TITLE
Add in-game chem recipe reference

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1092]
Add to the PDA or another tablet a list of all the chemical recipes from the code, provide them with comments directly in the datum that will be displayed there.

**Comment by NanakoAC** [comment]
Discussed this with clock. I will probably take this on in future.

The plan is to add a modular computer program to accomplish it, for consoles and laptops. Not for PDA.
Ill probably make it downloadable to anyone

**Comment by ACCount12** [comment]
MIRC is that thing.
