### ISSUE TITLE
Financial security

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1113]
Vending machines and ATMs should take a photo everytime someone buys something of performs a bank operation. Log the operation as well, and make it accessible for cargo and/or security.
That way, security can find out that it was this fat cunt Frank who took all the donuts there is a masked guy who bought ten guns using three different IDs.

**Comment by ACCount12** [comment]
Vendor transaction log now exists in cargo console. No photos though.
