### ISSUE TITLE
Ammo boxes

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1121]
Ammo boxes should be the same as of colonial marines server. Its really simple to use them there, one just need to click with a magazine on a ammo box and its boom, its refilled. There should be around 300 rounds in each ammo box. It would be nice to refill these boxes somehow, but its not utter at all.

Also, ammo system of colonial marines is nice overall.

**Comment by SpadesSlick** [comment]
Was made already.
