### ISSUE TITLE
Borked UI in PDA, cartridges field.

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#1148]
![image](https://user-images.githubusercontent.com/9161564/32506356-6739a45e-c3f5-11e7-83e8-a0aa3ee829ed.png)

**Comment by seekin4u** [comment]
https://github.com/discordia-space/CEV-Eris/blob/master/nano/templates/pda.tmpl#L55

https://github.com/discordia-space/CEV-Eris/blob/master/code/game/objects/items/devices/PDA/PDA.dm#L380
