### ISSUE TITLE
Making hardsuits not so useless

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1218]
Just add the ability to put satchels/backpacks on suit storage slot
Thats because common space suits/voidsuits are much better in terms of ergonomics now.

**Comment by NanakoAC** [comment]
i disagree personally, i'd rather see a storage compartment rig module.
Aurora had one, it was great, people started visiting robotics more often to get them made

**Comment by soslow4u** [comment]
I think we have no need for it, tbh.
