### ISSUE TITLE
Add contract system for some antags

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1241]
If someone knows if this feature is added in some build succesfully, add your note/opinion about it.

**Comment by NanakoAC** [comment]
Aurora had it, players could post their own contracts on a webform for antags to get ingame.

In practise it was very rarely used. Most of the contracts posted were very specific, usually people asking for their own characters to be kidnapped/killed for a challenge

In my view, the whole system was a monumental waste of development time
