### ISSUE TITLE
Putting things on distant tables is broken

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1244]
Hand sprite just gets an upper level over oxygen tank's sprite in HUD. Confirmation is needed, I dont know whats wrong with it 🤔 
https://cdn.discordapp.com/attachments/375588651599396866/384417191447232512/unknown.png
https://cdn.discordapp.com/attachments/375588651599396866/384417116897673216/unknown.png

**Comment by Voldirs** [comment]
Update: This bug is encountered when trying to click the table that not adjacent or blocked.
https://i.imgur.com/KHtee2G.png

**Comment by silentenemy** [comment]
Can't reproduce.
