### ISSUE TITLE
Fix chemical smoke, it fucks up the illumination and even more

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1245]
https://cdn.discordapp.com/attachments/375588651599396866/384418273036337162/unknown.png
Also, its a nice source of lags.
https://cdn.discordapp.com/attachments/375588651599396866/384449252350492674/image.png

**Comment by Voldirs** [comment]
After throwing two teargas grenades into the security lobby, the lighting will bug out and create a 3x1 row of darkness. Lighting equipment, such as flashlights, emergency lights, or even replacing the lighting in the security lobby, does not fix it, and only goes away after the round ends/resets.
![](https://cdn.discordapp.com/attachments/375588651599396866/402185036981469195/image.png)

**Comment by NanakoAC** [comment]
Probably related https://github.com/discordia-space/CEV-Eris/issues/1640
