### ISSUE TITLE
Chemical analyzer is slightly broken

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1253]
One can put pillbottle inside chemical analyzer and try to produce pills. Pills should appear in the bottle, but they do right on the turf for some reason. Interface is slightly broken too
https://cdn.discordapp.com/attachments/375588651599396866/384423666030739457/1df6597b20c0018927515780a9465396.png

**Comment by LagannPM** [comment]
Should be converted to Nano
