### ISSUE TITLE
Lobby voting needs fixing

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1256]
It spams that shit:
Error: You are not an admin.
Error: You are not an admin.
Error: You are not an admin.
Error: You are not an admin.
Error: You are not an admin.
Error: You are not an admin.
Error: You are not an admin.
Error: You are not an admin.
Error: You are not an admin.

**Comment by Dalekfodder** [comment]
I made a commit that fixes this, I will push soon

**Comment by Epicus7** [comment]
Is it still actual, @Voldirs?

**Comment by Voldirs** [comment]
It was fixed, I don't remind any other reports concerning this
