### ISSUE TITLE
Changeling regeneration is broken

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1259]
Confirmation is needed

**Comment by Dalekfodder** [comment]
This isn't correct, it is working.

**Comment by SpadesSlick** [comment]
Not fully. Broken limbs and organs not repairing, at least it was reported like that.

**Comment by Dalekfodder** [comment]
Ah, you guys need to put more details in your issues...

**Comment by SpadesSlick** [comment]
@Dalekfodder  you right. Someday there will be guidelines for issues.

**Comment by MrFoxik** [comment]
Fixed

> Your Changeling current objectives:
> Changeling ID: Mr. Zeta.
> Genomes Absorbed: 0
> Tip for a changeling: Merely killing your enemies with a shot in the back is so very droll. You can do better. Make them die tired.
> You feel something rip in your upper body!
> Something feels like it shattered in your upper body!
> Bluespace Technician screams!
> ADMIN LOG: mrfoxik/(Bluespace Technician) dealt 150 amount of brute damage to Bluespace Technician
> You feel broken bones moving in your upper body!
> Something inside your upper body hurts a lot.
> You feel a sharp pain in your upper body
> You feel extremely faint
> We will attempt to regenerate our form.
> Bluespace Technician gasps!
> Bluespace Technician gasps!
> Bluespace Technician gasps!
> Bluespace Technician seizes up and falls limp, their eyes dead and lifeless...
> You have died.
> grey baby slime (368) chirps, "Rawr..."
> We have regenerated.
