### ISSUE TITLE
Bluespace harpoon works strange

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1317]
Sometimes it just doesnt work (maybe it depends on Z-level where one attempts to do so), when placed in satchel it shoots and there is nothing indicating whether its ready for shooting or not.

**Comment by seekin4u** [comment]
Seems to be fine, this thing works properly right as it should work
![image](https://user-images.githubusercontent.com/24856443/38616446-bca4bf70-3d9c-11e8-8e70-ef55b04d25cc.png)

**Comment by seekin4u** [comment]
Z-level traveling is tested and it's fine now (except first you teleport to openspace and falls down)
