### ISSUE TITLE
Autopsy scaner is broken

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1413]
It doesn't show any traumas.
Confirmation is needed.

**Comment by LethalGhost** [comment]
Under normal conditions, it did not happen again.
Need more info.

![156](https://user-images.githubusercontent.com/2458675/35873676-32e89b5e-0b8c-11e8-975c-a68686311513.png)

**Comment by silentenemy** [comment]
Can't reproduce.
