### ISSUE TITLE
Making atmospheric "awakening" of the ship

### ISSUE THREAD

**Issue by Voldirs** [discordia-space/CEV-Eris#1447]
The idea is to make all lights on the ship OFF by default and if someone enters the zone (not roach or spider), all lights in that are turning on with flickerish sound. But lights should not turn on immediately. There should be interval between each lamp for maye second, half of second. Maybe some lamps should flicker a bit when turning on, that would be awesome too.

What that for? It would REALLY add an immersion of awakening ship, right now, it doesnt feel so. All systems are online by default.

**Comment by Guap6512** [comment]
Sounds great, and it's not difficult to implement.
