### ISSUE TITLE
Roach rework

### ISSUE THREAD

**Issue by silentenemy** [discordia-space/CEV-Eris#1468]
# Roachmap!
- [x] **First of all, move roaches out of `/mob/living/simple_animal`**

## Generic
- [ ] Burning roaches
- [ ] Add ability to tame roaches
- - [ ] Using fingerprints
- - [ ] Using FORCE FEEDING
- [ ] Add ability to breed roaches
- [ ] Add ability to give name to roach with pen
- [ ] Add ability to ride roaches
- - [ ] Limit it only to roaches with enough strength
- [ ] Add intelligent roaches which are controlled by players and don't require brain implants and racks
- - [ ] Let some subtype of them use their forelegs as arms

## ID
- [ ] Let roaches with ID attached open airlocks
- - [ ] Add ability to attach ID to roaches with duct tape
- - [ ] Show ID owner name as roach name

## Implants and prosthetics
- [ ] Add brain implants for roaches
- - [ ] Add ability to attach various items to roaches and hardwire them into their brains
- - - [ ] BEWARE! LASER-CARRYING ARMORED ROACH AHEAD
- - [ ] Add ability to **assume direct control** of roach via some kind of console.
- - [ ] Furthermore, add ability to ***undertake HIVE control*** via human brain implant: link roach brain implant to yours and call in reinforcements of roaches willing to kill for You, the Master
- - [ ] Add roach intelligence racks. You can insert positronic brains into them to give ability to assume direct control of roach, therefore letting ghosts play as roaches. But beware: if the rack is destroyed, roaches return to their default intellectual state
- - - [ ] Burn out roaches' brains with probability of something near 30% if their roach intelligence rack is destroyed
- [ ] Arm-like manipulators
- - [ ] *yeah see how I attach this ID to my pal, get ready to die, you mammal scum*

## Roach genetics
- [ ] Add genetic manipulations on roaches (like those in botanics: hybridization)
- - [ ] Stats system for roaches
- - [ ] Various mutations
- - - [ ] Reagents synthesis
- - - [ ] Layers of chitin
- - - [ ] ***ENLARGED*** mandibles

**Comment by bo20202** [comment]
😂🔫

**Comment by infraredbaron** [comment]
Add ability to wear hats
Plus genetics will benefit from using genetics as main way to manipulate roaches - this will give both genetics and xenobiology a proper task, instead of "criminal path".
