### ISSUE TITLE
Sort the plants alphabetically in MegaSeed Servitor

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#1569]
We need to make it more player-friendly.

**Comment by NanakoAC** [comment]
Title changed because #2043 fulfills part of this. So the title now reflects the part left undone

**Comment by NanakoAC** [comment]
my recent work on vendors didnt accomplish this, i'm done for now. Someone else is welcome to take a crack at writing a little sorting algorithm, i lack the time with other major projects to work on
