### ISSUE TITLE
Bugged virology centrifuge

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#1573]
If you insert blood into the centrifuge with the antidote and select the option "Antibody sifting", it will spin forever and do nothing.
![image](https://user-images.githubusercontent.com/9161564/41771978-98e80ea0-761f-11e8-959a-5078f7454d74.png)

**Comment by NanakoAC** [comment]
I stuck some blood in the centrifuge and tried this. After a minute or two it pinged and finished the job.

If this is still a problem can you provide exact steps to reproduce it?
