### ISSUE TITLE
Rebalance recharger

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#1584]
For now they are charge small batteries for too long, and large batteries can charge eternity. We must redo it, perhaps by adding a consumable fuel there instead of consuming energy from APC.

**Comment by NanakoAC** [comment]
do you mean it takes too long to charge, or that a charged battery lasts too long?
I dont think consumable fuel is a good idea. Stick with the APCs

Over on aurora I added entropy to chargers. I made them consume more power than they put into the battery (battery gets about 80% of energy drawn from APC, the rest is wasted)

**Comment by SpadesSlick** [comment]
Small cells are charged in seconds, big ones can charge for ages. And the last one is a problem.

**Comment by SpadesSlick** [comment]
Closed by #1660.
