### ISSUE TITLE
Disposal chutes are lower than conveyor belts

### ISSUE THREAD

**Issue by silentenemy** [discordia-space/CEV-Eris#1616]
![default](https://user-images.githubusercontent.com/5739068/43034820-5dab7168-8cec-11e8-94c9-8edfa6a4798e.png)

![default](https://user-images.githubusercontent.com/5739068/43034829-87de1e54-8cec-11e8-8518-36b8f5276c1e.png)

**Comment by NanakoAC** [comment]
I'll deal with this one

**Comment by NanakoAC** [comment]
fixed by #1643
