### ISSUE TITLE
Updated organs code flaws

### ISSUE THREAD

**Issue by LethalGhost** [discordia-space/CEV-Eris#1624]
Missed parts of new organs code:

[Bitflags for hands/feet](https://github.com/discordia-space/CEV-Eris/blob/master/code/__defines/items_clothing.dm#L101)

[Bitflags for termal protection division](https://github.com/discordia-space/CEV-Eris/blob/master/code/__defines/items_clothing.dm#L122)

[Stance handling](https://github.com/discordia-space/CEV-Eris/blob/master/code/modules/mob/living/carbon/human/human_organs.dm#L69), _Update counting or comments_

**Comment by LagannPM** [comment]
Will come with baymed
