### ISSUE TITLE
Grammar errors

### ISSUE THREAD

**Issue by silentenemy** [discordia-space/CEV-Eris#1648]
- [x] NeoTheology vendomat: **Teo**Mat
- [x] Kitchen dinnerware vendomat: cat **lunc**box
- [x] Railing: A standar**t** steel railing. Prevents from human stupidity.
- [x] Asters Miscellaneous Pack: `disk for autolathe designs.`

If you want to add some more, please, put `- [ ] ` before the text so there'll be a checkbox.

**Comment by praisenarsie** [comment]
![https://i.imgur.com/zWDYvVD.png](https://i.imgur.com/zWDYvVD.png)
circuits

**Comment by silentenemy** [comment]
- [ ] This is Bulletproof Vest.
capitalized somewhy

**Comment by praisenarsie** [comment]
![https://i.imgur.com/7Nx5FQv.png](https://i.imgur.com/7Nx5FQv.png)

removes

**Comment by Voldirs** [comment]
He has a robot Hesphaistos right leg. It hasa lot of dents!

**Comment by SpadesSlick** [comment]
Closed by #1659.

**Comment by Voldirs** [comment]
This is Alliance LG "Cog". 
It is a normal-sized item.
Alliance cheap laser gun. In our deep past - this was main weapon of low-rank police force across all Milky Way, b**ili**ons co**pys** of this gun was made. They still can be found alm**oust** everywhere.

@SpadesSlick that almost made me cry

**Comment by mistyLuminescence** [comment]
As of 21/7/19, all fixed.
