### ISSUE TITLE
Autolathe does not ejects materials loaded.

### ISSUE THREAD

**Issue by Faryaa** [discordia-space/CEV-Eris#1668]
Autolathe function to return sheets of materials loaded is broken. If you load it with stuff - it is there forever. Use it for printing or suck it up.

**Comment by Voldirs** [comment]
I had this bug, but somehow I was able to return materials later. Needs testing

**Comment by MrFoxik** [comment]
Fixed?

**Comment by mistyLuminescence** [comment]
Unable to reproduce as of 21/7/19.
