### ISSUE TITLE
Сделать хоть что-то страшное при засовывании БоХа в БоХ

### ISSUE THREAD

**Issue by PlinHost** [discordia-space/CEV-Eris#168]

**Comment by SpadesSlick** [comment]
А ты хорошо подумал про сингу на 5 зет уровнях сразу?

**Comment by PlinHost** [comment]
Ээээ нуу
Тогда надо запилить что-нибудь еще, но настолько же пидорасящее. И за одно проверить чтобы ингейм способа получания синги не осталось.

**Comment by SpadesSlick** [comment]
Потому что не происходит ничего. Необязательно взрыв, можно позже прикрутить к нему некоторые эффекты временной петли.

**Comment by SpadesSlick** [comment]
Issue will be redone later, when RnD rework will come.
