### ISSUE TITLE
Priest can be changeling

### ISSUE THREAD

**Issue by TheReduce** [discordia-space/CEV-Eris#1685]

**Comment by NanakoAC** [comment]
how is this a bug? Is there some reason he shouldn't be?

**Comment by NanakoAC** [comment]
this doesn't seem like a bug, no response

**Comment by SpadesSlick** [comment]
Well, cruciform should react to changelings violently. It's more like a feature that needed.

And priest should be blocked from roles with mutations and implants. Same for any cruciform owner.

**Comment by NanakoAC** [comment]
this issue has already been remade iwith a longer description, so we'll close this one
