### ISSUE TITLE
Table sprite issues

### ISSUE THREAD

**Issue by TheReduce** [discordia-space/CEV-Eris#1703]
![image](https://media.discordapp.net/attachments/375588651599396866/477902219186929684/2018-08-12_04_08_21-Space_Station_13.png)
![image](https://media.discordapp.net/attachments/375588651599396866/477901961891676170/unknown.png)

**Comment by NanakoAC** [comment]
how did this happen? I've not observed it being like that normally?

**Comment by TheReduce** [comment]
we don't give a puck now

**Comment by NanakoAC** [comment]
what?

**Comment by IlyaIII** [comment]
As an author of the first picture, could say that this glitch only occur when you see the table for the first time right after the round start. Byond 512 if that's important to note.

**Comment by NanakoAC** [comment]
then i'm inclined to say it's a byond bug, and beyond our control

**Comment by SpadesSlick** [comment]
Yeah, we can't do anything about that, let's just wait until Lummox will fix that.

**Comment by SpadesSlick** [comment]
I also believe it's a client problem.
