### ISSUE TITLE
openspace can have footprints on it

### ISSUE THREAD

**Issue by TheReduce** [discordia-space/CEV-Eris#1705]
![image](https://images-ext-1.discordapp.net/external/zPkG_YkxYVtZllkBIol7uggIWgTXPJ1ULhUD_-ivtII/https/image.prntscr.com/image/Y7qhbM2tQ4KWQkmDFrC3lA.png)

**Comment by NanakoAC** [comment]
it can also have blood splashes on it. I'm fixing both
