### ISSUE TITLE
VIP Bar access for IH Commander

### ISSUE THREAD

**Issue by Doloreere** [discordia-space/CEV-Eris#1707]
ironhammer commander hasn't got an access to alchogol vendor in V.I.P. bar

**Comment by NanakoAC** [comment]
is he supposed to have access?

**Comment by TheReduce** [comment]
v.i.p. bar for heads, i think he must have an access

**Comment by praisenarsie** [comment]
ironhammer operative isn't a head

**Comment by TheReduce** [comment]
commander*

**Comment by NanakoAC** [comment]
honestly, i say remove all access requirements from those machines.

If you can get into the place where it is, you should be able to guzzle alcohol from it
real beer taps don't have an ID swiper
