### ISSUE TITLE
Virology ejector doesn't send things into distance

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#1727]
https://i.imgur.com/AuNCopY.png

When you drop a monkey into a disposal tube which ejects into space, it should go flying into the horizon and never be seen again.

Instead, for some reason, these monkeys get fired about 3-4 tiles away and stop. Then your chat gets spammed as they suffocate and die while floating there. The spam continues as their bones break post mortem

I'd say anything that forcefully ejects into space should fly away and vanish, not linger near the hull

Not sure if this is due to external hull flooring providing friction (in which case it's a mapping problem) or disposal chutes not taking gravity into account (a coding problem)

**Comment by LagannPM** [comment]
Will come with baymed
