### ISSUE TITLE
Broken emote shortcuts (probably forced emotes as well)

### ISSUE THREAD

**Issue by fluorescent-net** [discordia-space/CEV-Eris#1753]
Any attempt to use emote shortcut (e.g. *gasp or *blush via "say") results in message with empty sender. I noticed this bug as well when I choked in maintenance tunnel and forcedly emoted with empty message. The cause is definitely in improper /mob/living/carbon/human/emote function behaviour which doesn't add source of emote in resulting message.

![default](https://user-images.githubusercontent.com/2707900/44313833-eb149d80-a417-11e8-98be-37e3b5be32a9.png)

**Comment by NanakoAC** [comment]
This is not fucking critical.
It is however my fault, and i'll fix it

**Comment by fluorescent-net** [comment]
You're right, I should have added a new and more relevant tag. However, I suppose that broken emotes is pretty important problem because it appears for any player and becomes obvious bug even without any further game interaction. Such an notable problem may simply scare off new players due to such a straightforward bugs not beign fixed.
