### ISSUE TITLE
Shotguns on the mining barge

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#1762]
At roundstart some shotguns are spawned on the mining barge. I feel that these are not very suitable for the following reasons

1. While guns aren't too hard to come by on eris, players are expected to take some risk by venturing into maintenance and battling through roaches. Getting guns from the mining barge is a bit too easy, afaik it's not too hard to break into even if you don't have access
2. They are presumably provided to allow miners to defend themselves against hostile creatures on asteroids. This is understandable, but gunpowder weapons are a poor fit for combat in a vacuum

I've seen on some servers that miners get a special gun which only works in a vacuum and is useless inside the ship/station. If miners are to be given a gun for free, something like that would make a better choice

**Comment by fluorescent-net** [comment]
>I've seen on some servers that miners get a special gun which only works in a vacuum and is useless inside the ship/station.

Tgstation had (and nerfed it as fuck) pneumatic cannon that was multipurpose upgradable tool. I can port it from /tg/reen, that was a lovely thing.

**Comment by fluorescent-net** [comment]
https://github.com/discordia-space/CEV-Eris/issues/1763
