### ISSUE TITLE
Port kinetic accelerator for mining and self-defence

### ISSUE THREAD

**Issue by fluorescent-net** [discordia-space/CEV-Eris#1763]
https://github.com/fluorescent-net/green/blob/72c52944fb6164f53c2bd9955d9c3a6cd45314f5/code/modules/projectiles/guns/energy/special.dm#L118

**Comment by NanakoAC** [comment]
it's for miners, for use in EVA combat fighting asteroid monsters, to replace their starting shotguns i hope
see the linked issue

**Comment by Voldirs** [comment]
I saw that. I don't understand what's the need in special weaponry for shooting in vacuum if one can use traditional weaponry. I can understand why it is so on TG, if one gives regular weapons to miners they would just get to station with them and wreak havok. But our situation is quite different, firearms are free to buy and carry at all times. I'd just leave these classic double-barreled shotguns, but lock them in a weapon locker, so assistant would have trouble just coming in and taking guns or much more valuable ammo.

**Comment by NanakoAC** [comment]
for uniqueness,for a start. Having things that are unique to a certain job makes that job more interesting to play
also because using gunpowder weapons in a vacuum doesn't really make sense

**Comment by fluorescent-net** [comment]
@Voldirs main point is kinetic accelerator is not actually a firearm but a perfect mining tool at first.
