### ISSUE TITLE
SMES Bypass switches inverted

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#1800]
According to a player today, the bypass switches on substations are working inversely. When bypass is enabled they go through the smes, when its disabled they go around the smes

**Comment by spaceplaceexplorer** [comment]
The way bypasses are mapped, is that they connect the SMES output into the SMES input when the bypass is enabled, meaning the power SMES receives is given back into the network. This works as intended after some tests.
