### ISSUE TITLE
Chemistry Storage is only acessible by ladder

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#1803]
This is kinda bad. It means that borgs, for one, can't use that room. Also anyone in a wheelchair

In general i'd imagine the chem storage room as being most useful for storing sources of reagents, like plants and animal corpses. so it should probably have some fridges too

**Comment by GrayRachnid** [comment]
Chemistry storage seems like it's not that important tbh and more of like an abandoned area.
