### ISSUE TITLE
Technomancer Exultant Hardsuit not working

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#1830]
A player got upset about this and quit. Apparently it won't deploy

**Comment by GrayRachnid** [comment]
I tried a few days locally and it worked?

**Comment by NanakoAC** [comment]
I dont know exactly, a player tonight tried to get it working and it wouldn't deploy. He got so upset he left the server :( We really can't afford to lose players, so i'll look into it thoroughly

**Comment by NanakoAC** [comment]
All rigs are broken, i'm fixing it
