### ISSUE TITLE
Deconstructing floortiles with an RCD leaves you with a different sort of space than the usual space

### ISSUE THREAD

**Issue by FlattestGuitar** [discordia-space/CEV-Eris#1882]
![2018-09-11_13-36-01](https://user-images.githubusercontent.com/15747030/45357776-a5d32e00-b5c7-11e8-87ef-598f79c69000.gif)

If there's nothing under a tile, it should turn into the cosmos kind of space, I'd say. This is a result of multi-z shenanigans.

**Comment by NanakoAC** [comment]
ill handle this while fixing floors. They are, in general, kinda broken

probably next week though
If you feel up to doing a short term fix in the meantime, please feel free

**Comment by NanakoAC** [comment]
fixed internally
