### ISSUE TITLE
Escape pods are broken

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#1906]
Override and Arm buttons when inside the pod do nothing

After launching and docking with the target station, the pod took forever to open

**Comment by GrayRachnid** [comment]
I think this is intentional to simulating taking off and docking time

**Comment by NanakoAC** [comment]
buttons inside the shuttle certainly aren't supposed to be broken.

The taking off and docking time are certainly simulated, there's audio for that. but those periods last like 20 seconds. The issue i'm talking about we were sitting on both ends for several minutes. It was far beyond the appropriate length of time.

I'm reasonably confident it had something to do with th shuttle being vented at the time, because some idiot got ahold of a gun and shot out a window in the shuttle waiting area
