### ISSUE TITLE
Drilling and Structure interactions need reworked

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#1942]
In general, all forms of drills and pickaxes should be moderately to highly effective at destroying walls and floors

I'm thinking implementing a new item var, structure_damage_factor, and checking it in damage interactions for walls, floors, windows, structures, etc. Drills should probably do about triple damage to structures

**Comment by katsukai** [comment]
I'm honestly against this, this really would remove all purpose of trying to deconstruct walls with tools that already exist and would be really abused to the point that people would only fight in EVA suits. I understand if you want to add this structure_damage_factor for firearms against walls and maybe floors but this wouldn't be a good idea with melee weapons that is very available to get. If this is intended for miners or retrieving space derelicts think there should be a specialized tool for this to breach walls and floors.

**Comment by NanakoAC** [comment]
Drills are tools, and powerful drills aren't broadly available. A drill is the weapon of choice for opening a bank vault, ever play payday?
yes there's a specialised breaching tool, thats for engineering and paramedics. Drills are for miners, providing an alternate option for dealing with obstacls

**Comment by katsukai** [comment]
This isn't payday and I doubt alloy made from this age would be destroyed by a handheld pickaxe. Imagine a mining borg with lawsets to kill would able to cause damage to the ship if floors and walls could be destroyed with those tools. This just gives a lot of room for people to grief and cause havoc with no real effort. Someone could just do that to the spawning area and stop spawning all together. If you really intend adding this feature you should consider adding walls and floors that aren't breakable by mining tools.

**Comment by NanakoAC** [comment]
hey chill out.
walls aren't meant to be indestructible barriers, last i checked you could destroy a normal wall with just a fire extinguisher
Alloys from this age can be used to make tools too
it won't be lacking in real effort or be overly available. Simply put, drills are heavy things that are designed for breaking hard objects
