### ISSUE TITLE
Access to R&D and Medbay for Moebius staff

### ISSUE THREAD

**Issue by Walfanger** [discordia-space/CEV-Eris#1975]
"Since research and medical are both part of moebius, allow them to work closer by giving people in both departments partial access into the other one. Just into the hallways and common areas, not into places like surgery or robotics. But more access than a normal person has, so they can go in and socialise with their colleagues"

**Comment by spaceplaceexplorer** [comment]
fixes https://github.com/discordia-space/CEV-Eris/pull/2046
