### ISSUE TITLE
Bugs with roles

### ISSUE THREAD

**Issue by Walfanger** [discordia-space/CEV-Eris#1980]
![ae0d4930c811d3999622ecbc941fc06f](https://user-images.githubusercontent.com/33196021/45929451-5280b880-bf95-11e8-8ba5-c0d52b5d887b.png)

"Two spawn buttons at storyteller panel. One of them are toggling spawn, other one is spawning that role by force"

"Borrer still spawning with role offer"
"I can't give role to some one directly using Traitor Panel, it missing a shitload of things. Maybe we should move it to storyteller."

**Comment by Epicus7** [comment]
>"Two spawn buttons at storyteller panel. One of them are toggling spawn, other one is spawning that role by force"

I have fixed it in 61653c5a95fc195056a165af272e430fc4c7e3f7

**Comment by LagannPM** [comment]
Is it fixed or not ?

**Comment by SpadesSlick** [comment]
Fixed.
