### ISSUE TITLE
Transformation of Angels

### ISSUE THREAD

**Issue by Walfanger** [discordia-space/CEV-Eris#1996]
"As ghosts are being reworked to Angels, add ability to Angels, to transform into the Seraphim(or how you want to name it)
Key feature is that Seraphs will be unavailable to interact with machinery like usual angels, but they'll be scout-angels and can provide vision for angels without cameras present.
Transformation cannot be reverted."

**Comment by NanakoAC** [comment]
The angels concept has barely been discussed with me at all, it may be an abandoned idea, at the very least it's on hold and in need of farther design

**Comment by SpadesSlick** [comment]
They were meant to be one of the roles for ghosts. Since they were plained for cyberspace, there is no reason to work on them until we have that system.

That issue is pointless so far.
