### ISSUE TITLE
Make mobs AI more smart

### ISSUE THREAD

**Issue by Epicus7** [discordia-space/CEV-Eris#2000]
Now mobs are pretty stupid. They choose the target and pursue it, no matter what is going around them.

I think that we need to introduce a system of priorities for the mobs, which will be based on danger and any other parameters, specific for each mob. They will try to attack more prior target, or even escape.

**Comment by praisenarsie** [comment]
Happy #2000th issue/pr

**Comment by NanakoAC** [comment]
Redesigning mob AI is not an easy or quick task.
Unless you're volunteering to take it on personally, this won't happen anytime soon
