### ISSUE TITLE
Fire extinguishers don't put people out

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2001]
Burning people continue burning after being sprayed

**Comment by NanakoAC** [comment]
turns out they do work, but badly. Very, very very badly. Something to do with how reagents are transferred, woring on it

**Comment by NanakoAC** [comment]
Cups/Lagann will handle this as part of overhauling chemistry and medical, we'll look into it again after that

**Comment by spaceplaceexplorer** [comment]
fixed in https://github.com/discordia-space/CEV-Eris/pull/2199
