### ISSUE TITLE
CE Hardsuit isn't fireproof

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2002]
Chief engineer burned to death in his hardsuit. The environment wasn't even that hot

While it protected fine against environmental heat, flames on his character directly caused damage

**Comment by NanakoAC** [comment]
unable to reproduce in testing, setting someone on fire will let them build up temperatures of over 5000 celsius (which is silly) but being in a CE hardsuit still makes you completely immune to the damage

I did see the CE die in live though, its either user error or i'm missing something

**Comment by GrayRachnid** [comment]
If he had no internals connected he'd still die. Hot environments aren't safe for breathing.

**Comment by spaceplaceexplorer** [comment]
I have replicated this issue in toxins burn chamber. These are the atmos stats in the room.
Pressure: 10263.5 kPa
Oxygen: 0% (0.12 moles)
Carbon Dioxide: 79% (311.92 moles)
Plasma: 20% (79.28 moles)
Temperature: 7617.2°C (7890.3K)
Heat Capacity: 151295

Hardsuit fully activated, internals on, fire resistant gloves.

**Comment by spaceplaceexplorer** [comment]
I have replicated this issue in toxins burn chamber. These are the atmos stats in the room.
Pressure: 10263.5 kPa
Oxygen: 0% (0.12 moles)
Carbon Dioxide: 79% (311.92 moles)
Plasma: 20% (79.28 moles)
Temperature: 7617.2°C (7890.3K)
Heat Capacity: 151295

Hardsuit fully activated, internals on, fire resistant gloves.

**Comment by spaceplaceexplorer** [comment]
It could be that the suit got punctured/damaged, there seems to be repair functionality implemented, so damaged suits is a logical conclusion.

**Comment by NanakoAC** [comment]
It's possible, we'll keep this open for now.

IIRC the player in question has the Ckey "Absolutely" and he plays a fat character.  Ask him for more information if anyone gets the chance
