### ISSUE TITLE
Cannot place cable on "underplating"

### ISSUE THREAD

**Issue by spaceplaceexplorer** [discordia-space/CEV-Eris#2007]
Fueltank blew up cable underneath a catwalk, I have removed the catwalk and could not replace the cable. I could not place a tile over it either, I could only rebuild the catwalk using rods. Cables cannot be placed on catwalk.

![cannotplacecable](https://user-images.githubusercontent.com/43578989/46022315-e6579f00-c0d1-11e8-828c-370be154556f.png)

**Comment by NanakoAC** [comment]
fixed internally
