### ISSUE TITLE
Supermatter radiation in kitchen/diner

### ISSUE THREAD

**Issue by spaceplaceexplorer** [discordia-space/CEV-Eris#2008]
Supermatter lacks proper shielding in direction of kitchen/diner, resulting in the entire area becoming irradiated when it's operational. Attached is an approximate radiation radius I drew. The radiation is not a perfect circle and seems to be affected by walls, in reality it stretches through the entire diner.

![radiation](https://user-images.githubusercontent.com/43578989/46027796-3dfc0780-c0de-11e8-9012-eec355220406.png)

**Comment by NanakoAC** [comment]
As far as I can tell from looking at the code, shielding doesn't exist. It's not a concept the supermatter is coded to factor in at all.
It irradiates everyone in a range based on its power, and that's all. This will need some redesigning

**Comment by SpadesSlick** [comment]
I'm not even mad about that, it's actually fits the ship lore pretty nice.
