### ISSUE TITLE
Multiple hardsuit bugs

### ISSUE THREAD

**Issue by spaceplaceexplorer** [discordia-space/CEV-Eris#2009]
1. Hardsuit maintenance port cannot be crowbar open/closed despite being unlocked. Despite this, I had managed to open the hatch on a previous build, but was unable to close it again.

2. Hardsuit head/chest/glove/feet pieces can be unequipped by hand but not dropped, it should not be possible to unequip them by hand.

3. A fully deployed hardsuit control module (backpack slot) can be unequipped by hand, quickly retracting it but making it unable to be dropped until reequipped, fully deployed and then retracted.

4. Hardsuit modules do not function, f.e. meson visor despite being turned on, will not provide 'mesonic' green vision through walls.

**Comment by NanakoAC** [comment]
thats a lot of issues, oh dear

**Comment by NanakoAC** [comment]
removed point 5 as per comment on #2133
