### ISSUE TITLE
Z-level spanning cables do not propagate power network properly

### ISSUE THREAD

**Issue by spaceplaceexplorer** [discordia-space/CEV-Eris#2013]
Pictured green cables have no power, above and below this z level they are powered.

![cableconnection](https://user-images.githubusercontent.com/43578989/46033001-989c6000-c0ec-11e8-8815-7d3b0ce6f856.png)

**Comment by NanakoAC** [comment]
Are you able to reproduce this in local testing? We currently have an issue where powernets across zlevels randomly become disconnected from each other, it's not specific to any cable

**Comment by spaceplaceexplorer** [comment]
To reproduce this bug: start a fresh server, connect the red and green cables at the same spot as in picture, then cut them. Take power measurements before and after connecting and cutting. Notice how prior to cut, red had a different power level than green, after the cut, only red has power and green has none.

**Comment by spaceplaceexplorer** [comment]
To reproduce this bug: start a fresh server, connect the red and green cables at the same spot as in picture, then cut them. Take power measurements before and after connecting and cutting. Notice how prior to cut, red had a different power level than green, after the cut, only red has power and green has none.

**Comment by spaceplaceexplorer** [comment]
To reproduce this bug: Start fresh server, connect red and green cables as pictured, then cut the connection. Notice how prior to the new connection both cables had power, after the new connection is cut, only red cable has power.

**Comment by spaceplaceexplorer** [comment]
To reproduce this bug: Start fresh server, connect red and green cables as pictured, then cut the connection. Notice how prior to the new connection both cables had power, after the new connection is cut, only red cable has power.

![cabletest](https://user-images.githubusercontent.com/43578989/46036290-b077e200-c0f4-11e8-8305-b603aa3a4889.png)

**Comment by spaceplaceexplorer** [comment]
Baystation seems to have a much cleaner implementation of z level spanning cables

https://github.com/Baystation12/Baystation12/blob/68a362c2c559d1eabd1c9d2bcb7e1a09d4485476/code/modules/power/cable.dm

**Comment by spaceplaceexplorer** [comment]
It seems bay has indeed fixed this issue, here's a port from another server

https://github.com/PolarisSS13/Polaris/pull/3346
