### ISSUE TITLE
Shower does not update character sprite

### ISSUE THREAD

**Issue by spaceplaceexplorer** [discordia-space/CEV-Eris#2016]
Taking a shower and removing blood from your items will not update your sprite, items have to be unequipped and put back on.

**Comment by NanakoAC** [comment]
Human item updating code is a mess. 
On aurora i wrote a major project to fix it all. Never finished it. I worked on it on and off throughout a  year, never quite got it done. 

I hope to do it for eris, but it'll be a fair bit of work
