### ISSUE TITLE
Ship Shield mode Atmospheric Containment does not work

### ISSUE THREAD

**Issue by spaceplaceexplorer** [discordia-space/CEV-Eris#2017]
Ship shields charged to 100% with the Atmospheric Containment mode active do block atmosphere from escaping the ship through them.

Pictured is a breach which sucked all the air from a room despite having shields active at full charge with said mode active.

![shieldbreach](https://user-images.githubusercontent.com/43578989/46051353-83ddbd80-c128-11e8-92b0-2734a6590916.png)

**Comment by NanakoAC** [comment]
oh dear, i coded this, so my fault. didn't fully test every aspect

ill fix it eventually but anyone else who wishes in the meantime is welcome to go for it
