### ISSUE TITLE
Walls problem. CRITICAL?

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#2048]
Rory Brereton attacks the steel wall with the steel NeoTheology ritual knife and it breaks apart!
One hit, and i destroyed a wall, almost same effect works on floor.

С помощью стального, ритуального ножа НеоТеологии я одним ударом сломал ЖЕЛЕЗНУЮ СТЕНУ в тех. тоннелях, почти такой же мощный разрушительный эффект на полу.

**Comment by seekin4u** [comment]
This is ```/obj/item/weapon/material/knife/neotritual``` knife inherited from usual knife, which has 
```force_divisor = 0.3```, which we can nerf, but i have needed to attack steel wall 7-9 times to brake it. Besides, this knife does 0 damage to girders and can't attack plating or floor.
This is strong enough, but not critically imo.

Короче обычные стены он только еле-еле чикает, укреппленным стенам только перекусывает прутья, то есть делает первый шаг для их разбора, после не атакует. Мне здается есть ппредметы и более сильные, надо обсуждать это деррьмо, потому чтоо пулл с неррфом урона в два рраза я делать не хоочу.

**Comment by Voldirs** [comment]
Don't nerf weapons, but buff walls against melee attacks somehow.

**Comment by NanakoAC** [comment]
Weapons are going to be rebalanced to some degree in future anyways, this case may be a bit of both
i'll look into it and see
