### ISSUE TITLE
Brain layer problem.

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#2051]
I'm under brain.
Я под мозгом.
![sprite-0002](https://user-images.githubusercontent.com/21274357/46249564-ffdf4a80-c433-11e8-9ead-e061df6298d3.png)

**Comment by NanakoAC** [comment]
Intended behaviour for surgery. It needs to draw over the mob so you can pick it up after extracting it from a corpse

drawing over a standing mob is unfortunate, perhaps something can be done with the layer of laying down mobs to fix this
