### ISSUE TITLE
Robotic Storage Spam

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2060]
When a robot is put into robotic storage, the storage unit starts spamming the common channel with an announcement about it, every second, forever

**Comment by spaceplaceexplorer** [comment]
Cannot replicate locally. Need logs from related round. I suspect it was a telecomms issue.

**Comment by NanakoAC** [comment]
It was solved by deleting the storage unit. It's pretty likely a problem with that object.
This is a critical priority bug witnessed and confirmed by many people, it's going to need to stay open for now, until we either fix it or can be sure its gone

**Comment by spaceplaceexplorer** [comment]
The storage unit has an announcement radio inside of it.
