### ISSUE TITLE
VV character's saylogs are empty

### ISSUE THREAD

**Issue by Epicus7** [discordia-space/CEV-Eris#2065]
_moved from junkyard_

**Comment by seekin4u** [comment]
IMO we do not have say_logs in our humans, so maybe we need to port it ? 🤔

**Comment by seekin4u** [comment]
![image](https://user-images.githubusercontent.com/24856443/46270170-cf400380-c54e-11e8-8ae8-59589128a3d1.png)
![image](https://user-images.githubusercontent.com/24856443/46270188-e67ef100-c54e-11e8-8dc3-7b5f2c4673ed.png)
second screenshot has only this 2 vars

**Comment by drexample** [comment]
We don't have that as a feature. All of the says are logged into the same server log
