### ISSUE TITLE
Headset can be taked off from under the helmet

### ISSUE THREAD

**Issue by Epicus7** [discordia-space/CEV-Eris#2071]
But it can't be put on after that.

There is no same problem with screwdriver, for example. You can't take off/put on it when you are wearing helmet.

_// Moved from junkyard_

**Comment by seekin4u** [comment]
Wait until #2039 is merged to fix this issue.

**Comment by seekin4u** [comment]
All headsets have ```slot_flags = SLOT_EARS and body_parts_covered = EARS```
and screwdriver has ```slot_flags = SLOT_BELT | SLOT_EARS```
So it is the need to fix inventory's unequip verb or make headset not to cover ears (which is stupid shitfix)

**Comment by NanakoAC** [comment]
wait until after ghost is done with inventory overhaul before touching this, yea
