### ISSUE TITLE
You cannot cancel Pod Evacuation/Bluespace Jump

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2107]

**Comment by spaceplaceexplorer** [comment]
Cannot reproduce locally.

**Comment by GrayRachnid** [comment]
I found the issue. You cannot cancel them on the old C&C console, but you can do it on the modular computer console.

![image](https://user-images.githubusercontent.com/6613514/46378159-c04d7400-c668-11e8-82e0-624c8f75c2df.png)

I'll go ahead and remove the old C&C console later.

**Comment by spaceplaceexplorer** [comment]
Replace all removed old consoles with modular ones if you don't know what to put in place.

**Comment by GrayRachnid** [comment]
That's the plan
