### ISSUE TITLE
The AI cannot use the helm console to pilot the ship.

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2111]
Clicking direct control just resets the camera.

**Comment by spaceplaceexplorer** [comment]
This seems to be intentionally enforced in code. It can still use autopilot.

**Comment by silentenemy** [comment]
#1656

**Comment by spaceplaceexplorer** [comment]
Cannot fix until https://github.com/discordia-space/CEV-Eris/issues/1965 is fixed
