### ISSUE TITLE
HUD issues.

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2118]
AntagHUD has no icons.
Not all jobs have SecHUD icons.

**Comment by NanakoAC** [comment]
Back on aurora i remade all of the security hud icons
![hudicons](https://i.imgur.com/PZ7QACI.png)
They are larger than the original ones, a necessity to fit any kind of information in. 10x10 each, but they look good with reduced opacity and correct positioning
