### ISSUE TITLE
Card-locked lockers can have their locks toggled from a distance.

### ISSUE THREAD

**Issue by eg0nSpengler** [discordia-space/CEV-Eris#2127]
Steps to reproduce.

1.  Have a card-locked locker within your vision range.(Card-locked lockers are Personal closets/ Department head lockers/etc.)
2. Alt-click to lock/unlock (If you don't have the required access for the locker, it wil still provide you the 'Access Denied' message.
3. Marvel at your newfound telekinetic powers

Another issue I noticed is that with the cell lockers inside the Prison/Brig cells (which are unlocked to begin with), locking them will immediately reset the lock to unlocked again.

**Comment by spaceplaceexplorer** [comment]
Prisoner lockers are controlled by the door timer system, they auto lock/unlock based on sentence status.
