### ISSUE TITLE
Add job description in preferences

### ISSUE THREAD

**Issue by LagannPM** [discordia-space/CEV-Eris#2140]
Could be ported from baystation
![img](https://cdn.discordapp.com/attachments/492848596853587997/496899501404061696/unknown.png)

**Comment by GrayRachnid** [comment]
This would help giving people an idea while we don't have a wiki for every single job.

**Comment by NanakoAC** [comment]
Yep, we just need lore descriptions to populate it

and to port that feature of course, but i think the content will be the hard part
