### ISSUE TITLE
Catwalks in space do not stop involuntary movement

### ISSUE THREAD

**Issue by spaceplaceexplorer** [discordia-space/CEV-Eris#2147]
Unlike a lattice in space, walking over/next to a catwalk, even with magboots on, will not let you 'stick' to it and you will simply float away as if it was not even there.

**Comment by NanakoAC** [comment]
working on it in zmovement project

**Comment by spaceplaceexplorer** [comment]
duplicate of https://github.com/discordia-space/CEV-Eris/issues/1663
