### ISSUE TITLE
Roaches can spawn in airless maintenance areas

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2150]
![example](https://i.imgur.com/CrF0D9U.png)

This area is literally open to space
Location is 82, 146, 1

there's a roach spawn placed here, they die immediately at roundstart
It'll never be seen during gameplay so doesnt even add atmosphere

For the record, it's a really bad idea to have pipes and wires running through space

**Comment by spaceplaceexplorer** [comment]
How about replacing those 2 grilles for windows?

**Comment by NanakoAC** [comment]
ehh,wouldn't be much point, it's still a sealed off and entirely inacessible area, afaik. it's not really going to have atmos

**Comment by spaceplaceexplorer** [comment]
It has atmos, it just vents at start because of the 2 grilles. There are many such inaccessible areas you have to dig through walls to reach.
