### ISSUE TITLE
Detective and Forensics are too far apart

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2152]
Forensics and the Detective are jobs which are closely tied together. They need to share evidence and communicate
Usually, on most servers they share an office and access, maybe even are just alt titles of the same job

On eris, the detective (inspector) has not one but TWO grand sized offices. Really his second office is huge, why is it so huge
![Detective Offices](https://i.imgur.com/zRSQVtf.png)

The forensics lab is a dingy corner hanging out into space, it can barely be called a corridor let alone a room. And worst of all, it's two floors below the detective. To get there he has to walk through the prison
![Forensics!](https://i.imgur.com/7BQRMZs.png)

sharing things is impossible. 

Forensics, being the smaller area, should be moved.
But to where?
Directly below detective is the prison, no space there. 
Directly above, is the VIP bar and moebius overseer quarters. So no space there.
It has to be on the same Zlevel

I see three possibilities. Not all exclusive either:

1. Reuse existing space. The detective doesn't need this much space. Turn his back office into the forensics lab, or part of it. The whole area could be repartitioned into three decently sized rooms

2. Expand north
Just north of the detective, there are thesetwo maintenance areas ![The hole](https://i.imgur.com/U5NowJ8.png)
They seem designed to form a corridor leading to a room just offscreen to the west, known as The Hole in the russian comunity. It's full of roaches and apparently popular for execution or corpse disposal.
But these corridors dont need to be that big. If the teleporter room were moved a bit north, so too could the corridor door be, and then the detective offices could be expanded north a bit, creating more space to fit forensics in

3. Expand west
![space](https://i.imgur.com/a8Kvm7f.png)
To the west is a big open area of space. Telecomms is visible to the south there, and the hole is north
The offices COULD be expanded into that area.

However, i'm not in favor of option 3, because i'd rather see telecomms moved to the north and into that space, to create room for a docking port where telecomms is currently sitting

**Comment by Voldirs** [comment]
In my opinion, inspector's office is fine as it is. I would like to see left room smaller a bit or filled with more content. (I noticed 2 closets there so there might be 2 inspectors instead of one, isn't it?) It looks like a good room for civilized interrogations and general conversations of investigation team. Forensics lab should be separated because that way inspector will have to handle forensics to medical specialist which sounds good to me.

**Comment by Voldirs** [comment]
They should separated so it's harder to get interrogation and forensics done by a single person. I think they should share access excluding lockers
For me, med. spec. is a set of three above with priorities depending on how much actual doctors and paramedics are present

**Comment by NanakoAC** [comment]
But that's an awful way to do things, throwing pointless frustration and inconvenience at players.

not to mention, interrogation and forensics are pretty rare as is, ironhammer is largely all about shooting. Anything that can be done to encourage it, should be

Restricting access would be the simplest way to prevent one person doing it, if that is the design

**Comment by NanakoAC** [comment]
They aren't at all "completely seperate" duties. They are nuances of the same duty, investigation

 They both heavily deal with evidence and solving crimes through deduction. They are close colleagues and should work together. The thing in the inspector's office that helps with forensics, is the inspector himself.  And neither the common channel nor the security channel are good places to discuss fine details of a crime scene, the latter will often be full of coordinating tactical movements

Both of them gather evidence, too, one swaps bloodstains and prints, one takes statements. They can't work in isolation from each other and hope to come up with any conclusion based on different forms of evidence. They need to discuss and compare, they need to meet in person, and they can't do that effectively with the current distance between them

And a minor matter, but worth mentioning. It's quite common for one of them to have to do both jobs. Especially during quiet hours, investigation is too niche of a job for two players, their facilities will often be operated by a single person.

Why should they be seperate? Seperating duties is certainly helpful, but these are duties with a lot of overlap, and where it's entirely possible for one person to have both skillsets. Having a seperate forensic tech isn't a given thing, on many servers it's just one role with alt titles. There's a reason for that, this kind of forced seperation just tends to lead to nothing getting done

**Comment by spaceplaceexplorer** [comment]
I thought inspector was more of a loose cannon working alone while forensics are part of a department.

**Comment by Faryaa** [comment]
I'm all for these. Inspector and Medical Specialist should be like Holmes and Watson(or Scully and Mulder). They should live and work closely together. Maybe give Medical Specialist the same revolver and a bit different coat/armour vest too? Labcoat is not something you should wear outside the lab.

**Comment by NanakoAC** [comment]
Clock has signed off on this project, it will be done

Also, Inspector is not only a part of ironhammer, but a middling officer, he outranks the operatives and they should obey his orders
