### ISSUE TITLE
Refactor obj/machinery/recharger or port it

### ISSUE THREAD

**Issue by ITCups** [discordia-space/CEV-Eris#2167]

**Comment by NanakoAC** [comment]
Ive made tweaks to our rechargers here.
What about them needs refactored? They're working well for our purposes

**Comment by LagannPM** [comment]
for example this should be replaced with something like get_cell()
![default](https://user-images.githubusercontent.com/6437377/46598876-dd25f380-cb0f-11e8-9b70-abd56f4c3375.png)
this should be in gripper instead
![default](https://user-images.githubusercontent.com/6437377/46598966-29713380-cb10-11e8-9530-6015c55f3462.png)

**Comment by NanakoAC** [comment]
ah, well maybe this can go with the rework of resource supply we discussed

**Comment by ACCount12** [comment]
Done in #4462.
