### ISSUE TITLE
Add sounds for human emotes

### ISSUE THREAD

**Issue by ghost** [discordia-space/CEV-Eris#2189]
For starters, *scream and *gasp

**Comment by NanakoAC** [comment]
We've discussed extensively but i'll state here for the record. This idea is a strong maybe, and is highly dependant on the quality of the audio files sourced for the purpose

Other servers have tried it with low quality scream sounds and it becomes a memeworthy failure

**Comment by NanakoAC** [comment]
![yes](https://i.imgur.com/gOvyQR1.png)

Add this feature in if you do add it. 2 might not be enough actually
