### ISSUE TITLE
Group Ritual PROBLEM

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#2206]
When i finished Crusade ritual (i made it only with one believer), i don't get new litanies, AND i no more can do other group litanies, they just don't work, if there is a cooldown, would be better if i see, how many time i need to wait, before another group ritual. 

Провёл ритуал на Крестоносцев (с одним верующим), не получил новых литаний, и БОЛЕЕ не мог сделать больше групповых литаний, они просто не работали. Если тут есть кулдаун на групповые литании, было бы неплохо получать оповещение о том, сколько осталось до возможности провести новый групповой ритуал. 

**UPD**

We tested these another time, and now we know one problem - group rituals work only once, second attempts to make other group ritual will fail, because cruciform won't react on litanies, any list of ritual members will not shown up to preacher, so... that sucks. 

Потестили эту фигню, короче ритуалы не работают второй раз, проповедник может завершить и сделать только один групповой ритуал, все остальные будут ПРОВАЛЬНЫМИ, по причине того что банальное количество учавствующих в ритуале и другие штуки не будут отписываться Проповеднику, и крестоформ не будет на это вообще никак реагировать, словно эти литании не имеют смысла.

**Comment by NanakoAC** [comment]
Well i see part of the problem here. Crusade respectively requires three, four and five people in total to unlock its abilities
