### ISSUE TITLE
Diner, Bar and Botany Redesign Plan

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2248]
Mapping Redesign Plan

Design goals and overview:
1. The bar needs to be close to the diner, people must eat and drink in the same place, this is vital for socialising
2. The lower garden will be opened up to the public and made more acessible. It is a comfortable social location. Anyone may use it for growing things or simply hanging around in
3. The botanist will be given their own section for plant splicing and private experimentation
4. Through removal of certain windows, the whole area will become a living, breathing heart of the ship. Three levels of shared atmos and travel without any doors

This area will be the centre of the ship both geographically and socially

Areas involved:

Deck 3:
	The diner and kitchen are here. North of the diner is a large maintenance area.
	North of the diner is also a single tile staircase leading downwards
	The east entrance of the diner goes past windows which overlook the small garden below.
	
	Changes:
		The maintenance area to the north will be converted into a new bar. The old bar will be removed, and that space probably repurposed
		The staircase down to the garden will be removed
		The windows overlooking the garden will be removed and replaced by railings, creating a more open-plan dining experience. This makes things more scenic and spacious
		A new staircase down to the small garden will be added by the diner entrance, on the south side of what used to be windows
		

Note: Magenta lines represent railings. Replace existing window-walls with railings in those spots, freeing up the tile for more space
![Upper deck 3](https://i.imgur.com/wO2JUuV.png)
![Lower deck 3](https://i.imgur.com/FoiNmT1.png)

Deck 2:
	The upper garden is here, and it is tiny. To its west is a staircase up to the diner, and windows overlooking the lower garden
	To the south of this garden is a significant maintenance area which is largely unused and contains a ton of ladders and walls
	To the north of this garden is a staircase which goes east and down to deck 1
	
	Changes:
		The staircase going up will be removed
		The staircase going down to deck 1 will be rotated 90 degrees anticlockwise
		The windows overlooking the lower garden will be replaced with railings
		The upper garden will be expanded a bit to fill this new space
		The maintenance at the south end will be converted into a botanist private area. 
		This area will have access doors into maintenance on either side, making it acessible from the underroad
		
![Lower deck 2](https://i.imgur.com/bDBkGBm.png)

	
Deck 1: 
	The lower garden is here, with a pointlessly spiralling corridor leading to it, and a checkpoint that locks it off
	Inside the lower garden
	The corridor needs to be cut down, and the stairway rearranged a bit.
	The doors leading into the garden need to be made public, the lower garden is a prime socialising area, beautiful and serene
	At the south and east of the lower garden, a hefty section will be claimed for private use of the botanist. A ladder or stairs will connect it with the upper private section

![Upper deck 1](https://i.imgur.com/EJHNPR0.png)
![Lower deck 1](https://i.imgur.com/s7g2oUr.png)

**Comment by spaceplaceexplorer** [comment]
I will assign myself once I actually start work on this.

**Comment by Jan-Blasiak** [comment]
What's the status? From what I've seen a lot changed since it was opened.

**Comment by TorinoFermic** [comment]
Redesign has been done by Reere
