### ISSUE TITLE
Ladder and some pipes going nowhere

### ISSUE THREAD

**Issue by spaceplaceexplorer** [discordia-space/CEV-Eris#2259]
Ladder near tcomm monitoring room above atmos.
![1](https://user-images.githubusercontent.com/43578989/47354939-9ad3e900-d6af-11e8-96f0-137de7ac9768.png)

Pipes underneath drone fab.
![2](https://user-images.githubusercontent.com/43578989/47354944-9d364300-d6af-11e8-917c-5295a845a86f.png)

**Comment by PJB3005** [comment]
![screenshot_20181111_151131](https://user-images.githubusercontent.com/8107459/48314077-97ec5a00-e5c4-11e8-8b64-19de27bc4a91.png)
![screenshot_20181111_151218](https://user-images.githubusercontent.com/8107459/48314079-9a4eb400-e5c4-11e8-8806-97aac6b1dd8c.png)

I used SDQL to track down the broken z pipes

```sql
SELECT /obj/machinery/atmospherics/pipe/zpipe/up WHERE !global._istype(node1, /obj/machinery/atmospherics/pipe/zpipe/down) &&  !global._istype(node2, /obj/machinery/atmospherics/pipe/zpipe/down)
```

```sql
SELECT /obj/machinery/atmospherics/pipe/zpipe/down WHERE !global._istype(node1, /obj/machinery/atmospherics/pipe/zpipe/up) &&  !global._istype(node2, /obj/machinery/atmospherics/pipe/zpipe/up)
```
