### ISSUE TITLE
Портировать /obj/item/device/communicator  с Поляриса

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#230]
https://gyazo.com/cd4ba4a05a99a85e1e414f33bb440237
Хорошая штука, братухе в бриг позвонить. В начале портировать, а позже лучше запихнуть его функционал в ПДА.

**Comment by dangranos** [comment]
Требуемые для коммуникатора файлы (и/или изменения в них)
- [ ] NanoUI: `nano/templates/exonet_node.tmpl`
- [ ] NanoUI: `nano/templates/communicator.tmpl`
- [ ] Еще NanoUI: `nano/css/shared.css`
- [ ] Exonet node, аналог телекомма для этого устройства: `code/game/machinery/exonet_node.dm`
- [ ] Communicator itself: `code/game/objects/items/devices/communicator/communicator.dm`
- [ ] `#define NETWORK_COMMUNICATORS`: `code/__defines/machinery.dm`
- [ ] Добавление коммуникатора в лоадоут + его настройки по умолчанию в `preference`: `code/modules/client/preferences.dm`, `code/modules/client/preference_setup/global/04_communicators.dm`, `code/modules/client/preference_setup/loadout/loadout_utility.dm`
- [ ] Описания в `code/modules/examine/descriptions/telecomms.dm` и `code/modules/examine/descriptions/devices.dm`
- [ ] "призрак в коммуникаторе": `code/modules/mob/living/voice/voice.dm`
- [ ] СОЗДАТЬ PULL REQUEST.

**Comment by SpadesSlick** [comment]
No longer relevant, we need to port full PDA and consoles rework from Bay first.
