### ISSUE TITLE
VV Runtime Error

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2352]
[00:54:05] Runtime in view_variables.dm,147: bad index
  proc name: make view variables value (/proc/make_view_variables_value)
  usr: Bluespace Technician (nanakoac) (/mob/living/carbon/human/bst)
  usr.loc: The floor (99,65,3) (/turf/simulated/floor/tiled/steel_grid)
  src: null
  call stack:
  make view variables value(/list (/list), "vis_locs")
  make view variables var entry(the screwdriver (/obj/item/weapon/tool/screwdriver), "vis_locs", /list (/list), 0)
  make view variables var list(the screwdriver (/obj/item/weapon/tool/screwdriver))
  NanakoAC (/client): View Variables(the screwdriver (/obj/item/weapon/tool/screwdriver))

**Comment by NanakoAC** [comment]
Some more of this

happened while doing stuff with a welder, while i had a VV window open for it 
[07:29:54] Runtime in view_variables.dm,147: bad index
  proc name: make view variables value (/proc/make_view_variables_value)
  usr: Caitlyn Stocker (nanakoac) (/mob/living/carbon/human)
  usr.loc: The floor (97,42,2) (/turf/simulated/floor/tiled/techfloor)
  src: null
  call stack:
  make view variables value(/list (/list), "vis_locs")
  make view variables var entry(the ported expanded custom spi... (/obj/item/weapon/tool/weldingtool), "vis_locs", /list (/list), 0)
  make view variables var list(the ported expanded custom spi... (/obj/item/weapon/tool/weldingtool))
  NanakoAC (/client): View Variables(the ported expanded custom spi... (/obj/item/weapon/tool/weldingtool))

**Comment by seekin4u** [comment]
`vis_locs` and `vis_contents` is new 512 variables. They are not used anywhere in this build, but make runtimes. I may suggest this is due to byond's own internal errors and/or beta-build.
So now we can only update byond in hope that they have been fixed properly and watch to our runtimes.
