### ISSUE TITLE
Captain's suit for fat body is drawn on mob's sprite when you are fully covered with rig parts.

### ISSUE THREAD

**Issue by seekin4u** [discordia-space/CEV-Eris#2400]
(These green pixels is the problem)
![unknown 2](https://user-images.githubusercontent.com/24856443/49472802-08c81000-f819-11e8-8b4f-95d937725073.png)
Check `/obj/item/clothing/suit/space/rig`'s item_flags for `HIDEJUMPSUIT` flag.

**Comment by Garen7** [comment]
fat body is removed so this isnt an issue anymore
