### ISSUE TITLE
Овермап, полет корабля на нем

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#241]
Для начала нужно оценить, насколько еблей будет его включение в билд. Затем решить, делать его сейчас или позже.

Овермап это отдельная карта, на которой корабль отображается обьектом в один тайл, как и все обьекты, вроде астероидов. Если корабль находится в одном тайле от астероида, то шаттл может добраться до астероида, иначе он не полетит.

**Comment by ModernViolence** [comment]
В MVP точно не входит.

**Comment by RiyaMakary** [comment]
Какая боль, самое вкусное в билде теперь в "отложенное"

**Comment by SpadesSlick** [comment]
Бей не столь давно обновил и вроде как починил овермап для Торча. Стоит глянуть, что они сделали.

**Comment by SpadesSlick** [comment]
Done.
