### ISSUE TITLE
Bible crash problem

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#2469]
I found the way, i can reproduce this bug. When you get new bible, you have ALL rituals, and group rituals at one page, if you do not click on "COMMON" or "GROUP RITUALS" buttons, then you get crash if you open one of group rituals.
For russian coders
Покупая новую Библию, и открывая её, ты получаешь полный список литаний, групповых и обычных. Не нажимая на кнопки "COMMON" и "GROUP RITUALS", сразу переходим к открытию групповой литании, которая находится в самом низу. Открываем. Крашим клиент. Побеждаем.

**Comment by NanakoAC** [comment]
There's no need for the second half of the issue. It's a requirement for all our coders to be able to speak english x

this seems like a good repro though

**Comment by NanakoAC** [comment]
I've confirmed that this issue happens when the category of the book gets set wrong. Instead of containing a name of a category, it contains some junk data, which confuses the browser in the client

**Comment by TorinoFermic** [comment]
In my testing, I found out few things.

The normal book looks fine except few things when opening 3 groups that causes the client to crash :

1. Robustness
2. Toughness
3. Crusade

Also, revealing Mechanical hides all groups rituals. [This video will show this.
](https://gfycat.com/HairySparseElkhound)

After you crash, the variable expanded_group contains the ritual that causes to crash you. Setting it to empty will make this book work again. 

In some cases, it also crashes NanoUI when interacting with this book or machines. Like this.
![dreamseeker_2019-02-02_17-47-22](https://user-images.githubusercontent.com/36856516/52170600-5a0e5600-271b-11e9-9278-fefdb65faf17.png)

2 files contains this variable "data["currexp"] = expanded_group" :

- code/modules/core_implant/ritual_book.dm
- nano/templates/ritual_book.tmpl
