### ISSUE TITLE
Food runtime

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2477]
[03:26:09] Runtime in Chemistry-Reagents-Food-Drinks.dm,29: list index out of bounds
   usr: Obren Komnjenovic (rosalimo) (/mob/living/carbon/human)
   usr.loc: The floor (115,91,6) (/turf/simulated/shuttle/floor)

Not sure what was involved here but rosalimo would know

**Comment by ACCount12** [comment]
Likely the same issue as #3871
