### ISSUE TITLE
Return of the Density Crash

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2480]
A couple months ago we had a horrible bug causing crashes on startup. This bug was eventually traced to a density check in wall/update_icon

Apparently, attempting to access the value of the density var would cause a crash, You couldn't read or output it in any way. Removing the line that checks density would fix it, but it is used for fake walls

We eventually managed to get it to stop crashing by deferring it until later https://github.com/discordia-space/CEV-Eris/pull/2287

However this solution seems to have stopped working, and it is crashing again

BUG: Crashing due to an illegal operation!
proc name: update icon (/turf/simulated/wall/update_icon)
  source file: wall_icon.dm,61
  usr: null
  src:  (67,54,2) (/turf/simulated/wall/r_wall)
  call stack:
 (67,54,2) (/turf/simulated/wall/r_wall): update icon()
the low wall (/obj/structure/low_wall): update connections(1, 0)

**Comment by hitsedesen** [comment]
The problem is not in the density line itself. It appears to be some kind of memory overflow.

**Comment by NanakoAC** [comment]
closing for now
