### ISSUE TITLE
limb reattachment surgery not working

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2500]

**Comment by Garen7** [comment]
You can replace the limb with a mechanical one, are you saying that using the original limb doesn’t work? I don’t think it is supposed to with baymed because of necrosis and all.

**Comment by NanakoAC** [comment]
This report was transcribed from junkyard, someone else reported it and i've not yet had the chance to take a closer look at it to confirm it

but i think yes they were saying that reattaching the original limb didnt work
