### ISSUE TITLE
Excelsior needs an intro

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2517]
the game explains very little about how excelsior are supposed to work or what their strategy is, players need more advice

**Comment by Wesreidau** [comment]
"Power is in inflicting pain and humiliation. Power is in tearing human minds to pieces and putting them together again in new shapes of your own choosing. Do you begin to see, then, what kind of world we are creating? It is the exact opposite of the stupid hedonistic Utopias that the old reformers imagined. A world of fear and treachery is torment, a world of trampling and being trampled upon, a world which will grow not less but more merciless as it refines itself. Progress in our world will be progress towards more pain. The old civilizations claimed that they were founded on love or justice. Ours is founded upon hatred. In our world there will be no emotions except fear, rage, triumph, and self-abasement. Everything else we shall destroy—everything. Already we are breaking down the habits of thought which have survived from before the Revolution. We have cut the links between child and parent, and between man and man, and between man and woman. No one dares trust a wife or a child or a friend any longer. But in the future there will be no wives and no friends. Children will be taken from their mothers at birth, as one takes eggs from a hen. The sex instinct will be eradicated. Procreation will be an annual formality like the renewal of a ration card. We shall abolish the orgasm. Our neurologists are at work upon it now. There will be no loyalty, except loyalty towards the Party. There will be no love, except the love of Big Brother. There will be no laughter, except the laugh of triumph over a defeated enemy. There will be no art, no literature, no science. When we are omnipotent we shall have no more need of science. There will be no distinction between beauty and ugliness. There will be no curiosity, no enjoyment of the process of life. All competing pleasures will be destroyed. But always—do not forget this, Winston—always there will be the intoxication of power, constantly increasing and constantly growing subtler. Always, at every moment, there will be the thrill of victory, the sensation of trampling on an enemy who is helpless. If you want a picture of the future, imagine a boot stamping on a human face—for ever."﻿ - Orwell, 1984.

I was playing Excelsior, reviewed the existing lore for them, and had a synthwave song with these words playing in the background. The result was an infiltrator sitting down with the priest trying to rationalize their worldviews. That I was able to have a candid conversation in private seemed wrong. I would think the implant should always broadcast what your character says to all other Excelsior, and you simply have the choice to stop hearing them. This is the opposite of our human experience; we always hear, but have the option to not speak. The implant lets them communicate to one another, but it also spies on them. They are never alone, they are always watched, they are always heard.

God must be a lie, for how can God make men equal yet some men have more? Are stronger? Are smarter? Where he is from, all are equal. You turn your eye from a pretty face toward an ugly one, it is obscene to note one person is taller than another, it is rude to eat less or more than your ration card. You do not decide what clothes you wear, all clothes are the same. Men and women wear the same clothes. Men and women have the same haircut. There is no difference between the sexes. There is no lipstick. There are no beards. He stressed the idea of radical egalitarian Marxism, removing man and woman and simply becoming human. He rebuffed the idea he was a Communist, he said he was a Humanist. They will abolish differences and so cease to be individual organisms, but instead, each comrade shall be a cell in an organ in an organism. The Hives are human organs. Humanity is an organism. God, money, inequality, happiness... these are all fever dreams and cancers in that organism.

When they have perfected the species, no human will be happier than the other. All will be united in grey misery and call it happiness. Any who dare say they are unhappy are clearly suffering the diseases of the past and must be amputated from the organism lest it spread.

And I would be delighted to write that up for you.

**Comment by NanakoAC** [comment]
Impressive writing effort, We should get you onto writing ingame books and articles.

This however, is not what i had in mind. The intro they need is more like that of the mercenaries - a 200 word description of their mechanics, playstyle and overall objectives, to give people something to go on. There's no room for lore in this particular case

I was planning to write it, as part of a broader project reanalysing excelsior and their mechanics

**Comment by Wesreidau** [comment]
You are _Excelsior_, Ever Upward. No longer tyrants and subjects, but comrades. No longer rich and poor, but equals. No longer beauty and ugliness, but faceless. Your goal is to free these fellow humans from the chains of power, greed and lust. One who is strong; cripple them. One who is wealthy, plunder them. One who is beautiful, defile them. Only when all are brought down together to equality may the collective rise ever upward.

**Comment by Wesreidau** [comment]
You are _Excelsior_, Ever Upward. No longer tyrants and subjects, but comrades. No longer rich and poor, but equals. No longer beauty and ugliness, but faceless. Your goal is to free these fellow humans from the chains of power, greed and lust. Gather the oppressed, the poor, and the ugly. Coordinate with your implants and manufacture the tools of your liberation. Find those who oppose progress. One who is strong; cripple them. One who is wealthy, plunder them. One who is beautiful, defile them. Only when all are brought down together to equality may the collective rise ever upward.

( More verbose. Edit me. I think a fast thematic blurb may be a better use since many players will soon know what Excelsior is, while a more in-depth description of mechanics and objectives belongs on a wiki so a new player can get all the info he needs. Trying to write a 200 word micro guide to the role will be hard to make thematic as well as informative. )

**Comment by Wesreidau** [comment]
You are Excelsior, Ever Upward. You have infiltrated this vessel to further the Revolution. Secure a base of operations, recruit fellow workers into the Party, and mass produce the weapons of your liberation. Only when all are laid low in equality may the collective rise ever upward.

( Further condensed after some more understanding of the role. )
