### ISSUE TITLE
SUGG: Make Compact Defibs a paramedic equipment instead of CMO unique. CMO is not a first responder and have no need in those, paramedic does.

### ISSUE THREAD

**Issue by Wesreidau** [discordia-space/CEV-Eris#2543]
From Ганс Шмульке

**Comment by Wesreidau** [comment]
SUGG: Make Compact Defibs a paramedic equipment instead of CMO unique. CMO is not a first responder and have no need in those, paramedic does.

**Comment by fernandos33** [comment]
do we even have defibs? havent seen one here since i started in cev eris
