### ISSUE TITLE
Sugg - Body Scanner for Surgery Room

### ISSUE THREAD

**Issue by Wesreidau** [discordia-space/CEV-Eris#2613]
The current surgery room is causing problems for surgeons. Hauling patients on a roller bed up and down stairs, then across three rooms to a scanner, takes a lot of time when a surgeon needs to verify their work. Since we have anesthetic tank stands, you have to detach and reattach the patient from the stand, put them onto a bed, drag them down the stairs, check them in a scanner downstairs, drag them back up the stairs, reattach them, etc. This led to someone in the hands of a capable player dying due to an unexpected bit of appendicitis flaring up while fixing a rib cage.

Putting a body scanner in the middle of the south wall will alleviate this.

**Comment by fernandos33** [comment]
its made that way so its harder for the doc. you shoukd print the 1st scan and gake it with you to the surgery room. and fix the patient (if you messes up the fixing you have to pay the "price" wich in medbay is directly converted to time.)

{time isn't money here. its health ehhehe}
