### ISSUE TITLE
Sparks don't work

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2620]
Spark system calls exist all over the code for all kinds of machinery.

Ours simply don't work, there are no sparks.

this is a real shame, they add a lot of atmosphere

**Comment by Wesreidau** [comment]
The igniters don't create visible sparks, yet they do ignite gas where one would expect them to.

**Comment by Wesreidau** [comment]
TEG sparks caused plasma fires today on tiles where you would expect them too. Sprite seems to be the problem.

**Comment by NanakoAC** [comment]
fixed
