### ISSUE TITLE
Jumping into space leads to asteroid

### ISSUE THREAD

**Issue by EvenInDeathIStillServe** [discordia-space/CEV-Eris#2624]
So, in a private server, I jumped into the disposal chute in front of the cargo bay. I kept jumping into chutes until I got thrown into space. After like 10 seconds of moving in space, I got teleported to the asteroid.

![image](https://user-images.githubusercontent.com/11510380/51121791-33da5200-1810-11e9-8413-4a6f0261baf6.png)

**Comment by EvenInDeathIStillServe** [comment]
I think that would answer the tiles, but there's still the issue of teleporting there when exiting the station boundaries.

**Comment by silentenemy** [comment]
Do you have overmap enabled in config? If no, this may cause such problem.

**Comment by EvenInDeathIStillServe** [comment]
I forgot to add in the config file to the config folder, so I'm assuming it's disabled.

**Comment by Wesreidau** [comment]
Overboard crew eventually washing up on major objects and getting rescued by the ship sounds like a way to create some gameplay.
