### ISSUE TITLE
BUG: Silver resource duping possible with protolathe.

### ISSUE THREAD

**Issue by Kurgis** [discordia-space/CEV-Eris#2652]
Within the Protolathe menu is the option for both advanced reagent scanners and spectrometers.
![brp1er](https://user-images.githubusercontent.com/35203040/51372242-7f1f8980-1aca-11e9-98ff-2865b115b845.png)
After printing, they come immediately with small batteries pre-installed despite costing no silver for printing.
![brp2er](https://user-images.githubusercontent.com/35203040/51372249-847cd400-1aca-11e9-876a-e7a6b4a0ddd7.png)
These can be recycled for silver after being removed, after which, you can recycle the devices themselves for a partial return on resources spent on the silver.
![brp3er](https://user-images.githubusercontent.com/35203040/51372258-8ba3e200-1aca-11e9-8acf-df919baf986d.png)

**Comment by NanakoAC** [comment]
ill fix this tonight
