### ISSUE TITLE
Gun turrets give infinite energy weapons

### ISSUE THREAD

**Issue by EvenInDeathIStillServe** [discordia-space/CEV-Eris#2688]
I destroyed an excelsior gun turret. While trying to disassemble it, I used a crowbar to pry out components. Accidentally double clicked, so the turret spawned 2 energy guns. I tried prying out components again and it kept spawning energy guns.

![image](https://user-images.githubusercontent.com/11510380/51475864-9933c300-1d7b-11e9-887d-0e6a186e453d.png)

**Comment by NanakoAC** [comment]
fixed in #2691
