### ISSUE TITLE
Moebius research starts with 3500 instead of the promised 5000

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2695]

**Comment by seekin4u** [comment]
3500 what? Crazy code-monkeys?

**Comment by GrayRachnid** [comment]
I forgot to mention that

**Comment by seekin4u** [comment]
Well this should be wasy to fix

**Comment by NanakoAC** [comment]
Yes i changed it, but where is 5000 promised?

They recieve additional funding every hour on top of that, 3500 is just a starting balance

**Comment by NanakoAC** [comment]
working as intended
