### ISSUE TITLE
BUG: Excelsior turrets do not recognize starting Excelsior leaders, only members that were later converted.

### ISSUE THREAD

**Issue by Kurgis** [discordia-space/CEV-Eris#2709]
Fishie#9762 reports experiencing this same problem as well. I've also tested it in-game with the use of excelsior shield generators on taser mode, I as a starting Excelsior, would be targeted by them. While a comrade I had converted earlier (who also created said turrets), was not targeted. Additionally, I had to have the excelsior turrets disabled, as they would target myself with their lethal rounds.

**Comment by NanakoAC** [comment]
fixed in #2690 
we will update the server tonight to get this live
