### ISSUE TITLE
[BUG] Items don't shatter

### ISSUE THREAD

**Issue by dashingzowie11** [discordia-space/CEV-Eris#2733]
When thrown, bottles and other shatter-ables do not break.

**Comment by NanakoAC** [comment]
not exactly a bug, more of a missing feature.

Adding this feature would not be a bad idea, but not a simple one. This would significantly affect balance with the vendor contents launching event, and also cause a lot of broken glass in disposals

**Comment by dashingzowie11** [comment]
i had an idea of recyclable trash shoots that would act like store bottle returns. maybe depending on how fast the object is moving is how much damage it takes.
