### ISSUE TITLE
Cell chargers can't be built

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2740]
We need the circuitboards for rechargers to be made available in circuit printer and maybe autolathe.
This circuit should also be added to random circuitboard loot lists, fairly common

Since these are small and non dense, they should probably be made via crafting rather than building machine frames.
In addition, we should add the ability to insert this circuit into a wall mounted frame (APC frame?) to create a wall recharger

**Comment by Garen7** [comment]
Do we have sprites for wall chargers?

**Comment by RandomColonist** [comment]
Not relevant anymore, they can be built now.
