### ISSUE TITLE
Protolathes can allow infinite duplication

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2748]
No idea how this happened
![NANI](https://images-ext-2.discordapp.net/external/FzN8JW-9DVf8hGxHcEhEMQErf0JCrt51Qw8Peq6qXZE/https/i.imgur.com/uxtIgqI.png)

it apparently allowed things to be constructed for free

**Comment by ACCount12** [comment]
Never seen it, never seen anyone abuse it, never seen anyone as much as replicate it. Could be fixed since forever.
