### ISSUE TITLE
Lube does not reset the floor's wet var after it expires.

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2755]
basically keeps floors lubed forever.

**Comment by NanakoAC** [comment]
Not a bug, it is intended to remain indefinitely

however it should be removed by cleaning that floor, or by removing the tiles

**Comment by GrayRachnid** [comment]
Tiles were removed when I encountered this, lube did not get removed along with them.

**Comment by MrFoxik** [comment]
Fixed #3510
