### ISSUE TITLE
Недоработки нового HUDа.

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#276]
- [x] Не была закончена кнопка сокрытия и открывания полного инвентаря, с хедсетами, броней и прочим.
  ![image](https://cloud.githubusercontent.com/assets/9161564/19625065/f0242038-9916-11e6-8357-21ba90f04975.png)
- [x] Экран контейнеров наезжает на сам ХУД, его нужно сместить вправо.
  ![image](https://cloud.githubusercontent.com/assets/9161564/19625082/562b6e40-9917-11e6-9011-f29374915ad9.png)
- [x] Репортились проблемы в оверлеях худа при крите. Необходимо протестить.
- [x] Переключение интентов на ctrl+[1-4] не влияет на худ.
- [x] Оверлеи худа странно реагируют на смену рук. Если речь идет о оверлеях наркотиков, то они пропадают на одно мгновение (тик, похоже), если взять в руки предмет или сменить их, а затем возвращаются. Экран контейнеров пропадает полностью.
Иконки наверху, слева имеют свойства пропадать при активности худа, а затем возвращаться.
#353
- [x] Spin view ломает Худ. (f34331e)
- [x] Имена слотов в окне раздевания мобов потерялись.
- [x] #351 ?
- [ ] Команда Change View Range не работает нормально у мобов, хотя работает у гостов. Оно используется на прицелах и прочих биноклях, так что пофиксить надо.
![image](https://cloud.githubusercontent.com/assets/9161564/21678248/0e4a949e-d34f-11e6-9a02-bcefc551e595.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21678262/195d6906-d34f-11e6-89a2-57f62e31c4b5.png)
- [x] Оверлей мезонок, термалов и прочих ПНВ лезет поверх ХУДа, но не всего, не задевая ряд добавленных тайлов для ХУДа. Лучше всего просто запихать его под ХУД, дабы он не красил его этим жутким оверлеем, тогда и пихать его на дополнительные тайлы не нужно будет. И вообще, лучше у мезонок сделать больше прозрачности.
![image](https://cloud.githubusercontent.com/assets/9161564/21678417/affac570-d34f-11e6-8e9b-dbac62c11d3b.png)
- [x] Когда инвентарь убран, это пустое место лучше всего занимать вот этой вот штукой:
![image](https://cloud.githubusercontent.com/assets/9161564/21678566/6c9d2efc-d350-11e6-96a3-9a4664accefe.png)
![image](https://cloud.githubusercontent.com/assets/9161564/21678576/7d88a55c-d350-11e6-9fac-2270d129022e.png)

**Comment by EkuDza** [comment]
Проблемы оверлеев при крите не зафиксированы. Нужно подробности.

**Comment by EkuDza** [comment]
Нужны тесты оверлея худа и экрана контейнеров. Баги сообщать сюда.

**Comment by LethalGhost** [comment]
UP!

**Comment by SpadesSlick** [comment]
Апдейтнул.

**Comment by SpadesSlick** [comment]
No longer actual.
