### ISSUE TITLE
Sugg - Rename Cruciform to Crucifix

### ISSUE THREAD

**Issue by Wesreidau** [discordia-space/CEV-Eris#2794]
Cruciform - Shaped like a cross. The sword had a cruciform guard.
Crucifix- A cross-shaped religious icon. The crucifix was set on the altar.

**Comment by Kurgis** [comment]
I believe your second description is incorrect, a crucifix would specifically refer to an icon of Jesus laid upon the cross.

**Comment by NanakoAC** [comment]
I'm against this, because cruciform is unique and interesting, it maintains certain connotationsm but isn't quite flat out copying. 

Neotheology is significantly inspired by abrahamic religions, but it is not directly christianity

**Comment by Kurgis** [comment]
I believe this should be closed personally as a crucifix, unlike a cross, would literally have an icon of Jesus upon it. While a entire following of people having little Jesuses on their chests is an amusing thought, I don't think it sets the right tone.

That isn't to be said that there isn't a place to discuss a re-naming of the "Cruciform", after all, cruciform means shaped like a cross. The cruci- in cruciform comes from latin, yet the "Cruciform" is a tau-cross, not a regular cross. The latin for the tau-cross would be cruxi-, so one could make the word cruxiform, the form of a tau-cross. This isn't a word in any use, however, and there'd be no reason I'd see they wouldn't extend an already existing word, cruciform, over to the form of the tau-cross.
