### ISSUE TITLE
IH Medspec stats.

### ISSUE THREAD

**Issue by Pariah919** [discordia-space/CEV-Eris#2806]
IH medspec stats are utterly horrendous compared to other doctoresque jobs (20 Bio makes them a straight worse paramedic because Para gets 20B 10R 10T) their weapons and access sucks compared to a normal Op. Their only purpose currently is to open up the forensics lab for the Inspector (who can just wedge a crowbar in the door after asking nicely because theres no medspec because nobody plays Medspec). Autopsy's aren't even unique to Medspec due to the presence of a kit for it in the morgue. Where it is even better due to the presence of a body analyzer telling you damage locations. Medspecs also shouldn't risk surgery without upgraded tools because a crit fail could kill their patient. I do not know of a stat spread that would fit their role while not making them better than other doctors however. Possibly 25B and 10T(or robustness) to represent they have some sense of combat training?

**Comment by NanakoAC** [comment]
The medspec is meant to be an all rounder, my recommended stats for them
15 Bio
15 Robustness
15 Cognition

cognition will be more useful in future

**Comment by Pariah919** [comment]
I dunno about 15 robustness. That would make them more robust than a IH op. Which would be odd for a medical spec.

**Comment by fernandos33** [comment]
i think medspec is indeed in a bad place i like what the role should do but for IH detective  is a direct upgrade from weapon to stats. the only thing like said before is about the forensics door.  and even if you ask for a weapom at armory a lot of times. they just wont give to you "medic? you want a gun? you heal no kill"
and like said
lower stats than paramedic and detective
worst starting weapon from the IH force
acces as much as a detective.
have to ask bay for medicine
autopsy is not unique
and even tho the forensics lab is "unique"
the detective starts with the forensics kit aswell.
