### ISSUE TITLE
SUGG : Examine Tab with OOC desc for everything.

### ISSUE THREAD

**Issue by TorinoFermic** [discordia-space/CEV-Eris#2808]
Screenshots found by Gray

![image](https://user-images.githubusercontent.com/36856516/52389625-530c7e00-2a62-11e9-962a-e276ddddef03.png)

This examine tab should describe for items's HOW in OOC color for the ease of user.

**Comment by NanakoAC** [comment]
i'm about 60% sure that we already have this feature, but its just not populated with content
Its a set of vars like description_fluff, description_antag, and so on

**Comment by RandomColonist** [comment]
> i'm about 60% sure that we already have this feature, but its just not populated with content
> Its a set of vars like description_fluff, description_antag, and so on

It was purposely removed because of (not sure) removing shitton of items. I think it would be neat to bring it back with items, armour and (most important) tool properties to no pollute chat.
