### ISSUE TITLE
BUG: Some tools have fucked up examine interaction

### ISSUE THREAD

**Issue by RandomColonist** [discordia-space/CEV-Eris#2829]
Multiple tools have this issue, confirmed on big wrench, for example:
Big Wrench has odd behaviour upon examine - it shows only item description which "If everything else failed - bring a bigger wrench.", but no name, icon or tool qualities.
Same applies to other tools, but i can't exactly remember to which.

**Comment by NanakoAC** [comment]
unable to reproduce
