### ISSUE TITLE
BUG: All mags are interchangeable between same caliber guns

### ISSUE THREAD

**Issue by Coureere** [discordia-space/CEV-Eris#2833]
ALL mags of same caliber are interchangeable. .45, 7.62, 9mm and so on. Checked on 7.62, exactly i used traitor STS, Kalashnikov and SAW because 7.62 is most used and frequent calibers for me to encounter. This bug basically means that you can load 80-round boxes into any rifle of the same caliber. I loaded entire box of 7.62 meant for SAW into Kalashnikov and it worked just fine. Same way you can interchange 20 round STS mags, 30 round Kalashnikov mags and 80-bullets SAW boxes in ANY weapon that feeds of 7.62. And now imagine that autofire merged and server updated and you can carry your STS in backpack and it fucking feeds of 50 or 80 ammo box and can autofire. And you can feed NT .45 pistol of SMG .45 mags. Same applies for 9mm pistols and smg - tested and prooved.

**Comment by Wesreidau** [comment]
Obviously all of our magazines are STANAG.

**Comment by ACCount12** [comment]
Was fixed by the addition of magwells, ages ago.
