### ISSUE TITLE
BUG: 7.62 uplink buyable mag/box issue

### ISSUE THREAD

**Issue by Coureere** [discordia-space/CEV-Eris#2836]
7.62 mag from uplink looks like mag but it actually named "box" and has capacity of 50 boolets. I thing this is ment as additional low-capacity mag for LMG. Same shit with interchangeable mags bug applies here, you can feed of this mag any 7.62 rifle and it's actually comes pretty cheap (2 or 4 crystals).

**Comment by RandomColonist** [comment]
Not an issue anymore, was fixed long time ago, there is only normal AK magazines in uplink now (as well as HV, ofc).
