### ISSUE TITLE
SUGG: Tool quantity/quality rebalance/additions suggestion (big)

### ISSUE THREAD

**Issue by Coureere** [discordia-space/CEV-Eris#2859]
1. Outright remove Asters Basic Tools Pack from assistant room, leave only Misc Pack. You can already buy it or find it in tunnels with great chance. Also you might want to lower starting resources. Free autholathe =/= free resources. Because what they do is stealing metal and glass from it.

2. Rise price for tools in vendors and randomize quantity OR remove multiple vendors/restrict it by access (move them to engineering storage or something like that so engineers will decide do they want guild making profit from this vendors - more cooperation possibilities).

3. Replace some percent of regular tools with makeshift variants in tunnels. Like, in addition to tool being old it can just became makeshift (see #2851). And the worst variant will be makeshift old tools. Still better than nothing.

4. About advanced tools - their balance is weird. You can craft a bunch for small price if you have disc, but if you don't - only scavenging left. So what i suggest is giving engineers a bunch of advanced tools. Especially Exultant. Or just give him disc with them, atlease. Cause it's logical for them to have it, they are involved in engineer-ish things more than anyone. RCD/Hatton is sure good things, but sometimes all i need as exultant is box of nice brand new advanced instruments.

5. Following same logic, slightly rebalance content of discs. For example, basic tools pack don't need multitool because multitool isn't really basical, it more belongs in vendors and advanced tools disc (just my opinion, discussable, i can explain it). Same goes for flamer. But this disc also lacks wire coils and simple tape. And advanced tools can use more advanced tools like flex tape, munchkin and so on.

6. Following same logic [2], add some advanced tools to science. I already mentioned that some tools can't be obtained besides maint looting. Maybe add it for a fair prise to protholathe designs? Like, you can spend fuckton of advanced resources to make advanced chainsaw/munchkin if you want it (and then sell it ofc).

7. Following same logic [3], add another toolset to uplink that will qualify like "advanced" and will cost twice or more of "cheap" (current) toolset. Make it also come in belt instead of unwieldy box. So you can pay 2 (i don't really remember) crystals for simple boxed set of tools or you can pay double and more for advanced brand new set of tools coming in the belt (with gloves too ofc). I don't think i need to explain that. Also you might want to add "disc" cathegory to uplink, but that's slightly unrelated.

**Comment by RandomColonist** [comment]
This is copy of suggestion under #2851 and primarily ment for Nanako for reconsidering tools balance as she makes steps in that direction (technomancers tools quantity change).
