### ISSUE TITLE
You cannot take off a RIGsuit that has internal storage off your back by yourself.

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2881]
Someone else has to take it off. Dragging it to your hand just opens the storage, so does clicking on it.

**Comment by Garen7** [comment]
I was able to remove the Security hardsuit while it had an internal storage by dragging it to my hand as long as the hardsuit was powered down. What kind of hardsuit was this happening with? Was there anything weird happening at the time?

**Comment by GrayRachnid** [comment]
Ah. This only applies to the ninja RIG. Might be intended? tell me to close if so.

**Comment by Garen7** [comment]
I found the cause of this and I’ll fix it when I get home.
