### ISSUE TITLE
You cannot implant subdermal armor implant into the chest.

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2883]
have not tested with other limbs. when you try the step to secure it with a cautery, it doesn't work. This might be fixed with baymed.

**Comment by GrayRachnid** [comment]
This can also be left until brainmed.

**Comment by Kurgis** [comment]
The wiki appears incorrect, you only need to do so with organs not implants. Implanting muscle implants without connecting them to the tissue allows them to operate for example. Not sure if the same applies to sub-dermal armor, or the sign of another bug.

**Comment by GrayRachnid** [comment]
I spent 30 minutes messing with it, trying out all things. Seemed like a bug to me.

**Comment by ArcaneCarrot** [comment]
Subdermal is dumb and special and wants to be installed after you retract the skin, iirc.

**Comment by SpadesSlick** [comment]
Is this even a thing anymore?

**Comment by ACCount12** [comment]
Implanting worked just fine for me in the last couple of tests.
