### ISSUE TITLE
Nanopaste does nothing when trying to heal artificial organs.

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2892]
Just doesn't work.

**Comment by GrayRachnid** [comment]
you can probably leave this until brainmed.

**Comment by fernandos33** [comment]
i ve lost more than a patient with heart damage  to it.

once i tried to make a heart transplant and yse that autosyringe to get the heartbeating. and it made so the guy got in a state wich he was dead and could not get up. but the scan qould say he was good. a truly abomination. and them some mod Ahealed him. and so his health would not go down even tho he would get hurt feel pain and gasp

both nanopaste and heart stuff need some looking

**Comment by fernandos33** [comment]
bump. wee need this

**Comment by infraredbaron** [comment]
PLZ FIX

**Comment by fernandos33** [comment]
https://github.com/discordia-space/CEV-Eris/pull/3568
