### ISSUE TITLE
Fuel/Water tanks and their High volume opposites have swapped sprites.

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2909]
Each one should have the other.

**Comment by Kurgis** [comment]
I've checked both `/obj/structure/reagent_dispensers/watertank` and `/obj/structure/reagent_dispensers/fueltank` along with their relevant `/huge` sub-type. Their icon states all appear correct, can you describe the issue further, or give an in-game screenshot of the issue?

**Comment by GrayRachnid** [comment]
The icons themself are swapped. The /huge one has a smaller looking tank but the normal one has a bigger looking tank. Put them next to eachother and you'll see.

**Comment by Kurgis** [comment]
![watertank](https://user-images.githubusercontent.com/35203040/53134475-4baaa180-3545-11e9-972d-69fc62ba8388.png)
![hvwatertank](https://user-images.githubusercontent.com/35203040/53134477-4c433800-3545-11e9-9809-e625ed94a75e.png)

I'm unable to see any issue, you'll need to point out the code lines, or give in-game screenshots.

**Comment by GrayRachnid** [comment]
Oh. Stupid me. I was thinking of the right black area as the holder of the water. Ignore me.
