### ISSUE TITLE
You can unwrench and remove an underplating's support beams as many times as you want.

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#2911]
![image](https://user-images.githubusercontent.com/6613514/52906110-a9707e00-3213-11e9-871b-167e05383972.png)

They'll never go away.

**Comment by GrayRachnid** [comment]
After further testing, underplating is broken.

**Comment by ACCount12** [comment]
Same issue as #4163. Fixed by #4306.
