### ISSUE TITLE
NTNet runtime

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2921]
[23:23:44] Runtime in NTNet.dm,256: Cannot execute null.getProgramByType().
  proc name: create email (/datum/ntnet/proc/create_email)
  usr: The new player () (/mob/new_player)
  src: /datum/ntnet (/datum/ntnet)
  call stack:
  /datum/ntnet (/datum/ntnet): create email( (/mob/living/carbon/human), "faith.styles", "cev_eris.org")
  Jobs (/datum/controller/subsystem/job): EquipRank( (/mob/living/carbon/human), "Ironhammer Commander")
  the new player (/mob/new_player): AttemptLateSpawn("Ironhammer Commander", "Aft Cryogenic Storage")
  the new player (/mob/new_player): Topic("src=\[0x30000f3];SelectedJob=I...", /list (/list))
  NanakoAC (/client): Topic("src=\[0x30000f3];SelectedJob=I...", /list (/list), the new player (/mob/new_player))
  NanakoAC (/client): Topic("src=\[0x30000f3];SelectedJob=I...", /list (/list), the new player (/mob/new_player))

This happens when spawning as many ironhammer roles

**Comment by Garen7** [comment]
Do you know anything about how to reproduce this? Does it only and/or always happen to only certain jobs? Did the player's loadout have any modular computers in it? Does the round time/player count affect this?
