### ISSUE TITLE
Email lacks notifications

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#2922]
There are no audible sounds or flashing images on your PDA to indicate that you have a new Email. This leads to nobody noticing when they get one, and thus very little use of the feature

**Comment by GrayRachnid** [comment]
You do actually get a notification, only when the Email client is left open/minimized

**Comment by GrayRachnid** [comment]
Also, I don't think this deserves the important label.

**Comment by Kurgis** [comment]
AI and cyborgs are the most responsive via e-mail, due to them being unable to turn them off. Power usage from the e-mail client could be edited out (if there is any), and could be made so you are no longer able to close the program.
