### ISSUE TITLE
Scrap: Missing mechanics and suggestions

### ISSUE THREAD

**Issue by DeLaFlash** [discordia-space/CEV-Eris#2978]
After an evening of testing with Course, we found a number of issues with scrap PR. 

First - Clothing piles. Most of broken stuff is probably being fixed as I write this, so this is suggestions. Rig parts have random "oldification" properties and actually can have contamination that can not be removed. And also can appear as new from old rig module. 
Old huds work perfectly fine, maybe add some distortion effects for their respective elements or make them display wrong info.

Second - gun piles. As I mentioned earlier, old guns function the same as new. Which should be fixed. Ammo doesn't spawn. At all. Not inside guns, not in boxes, not in magazines, just empty. All guns are empty by default, even magazine-based ones and energy guns. 

Suggestion: Make old guns jam, old cells and ammo have a chance to explode on use. 

Third - food and medicine. All food, even ancient, is perfectly safe to eat. Reagent contents perfectly match their fresh counterparts. Same with medicine - there are no labels on pill bottles, but all of them are safe, even century-old dylovene. 

Suggestion: make old food and drinks have a high chance of being poisoned, old reagent bottles and syringes have random reagents instead of marked ones (and possibly AIDS), old bandages infecting wounds and so on

Fourth: Industrial piles. Mechs are fine, but you can't find any equipment for them. Maybe make it spawn in industrial and be faulty in some way too? Old mods are the same as new, maybe make them a bit worse and/or harder to attach? Also it was noted that too many nuclear cells spawn. That probably should not be like that. 

Seems to be everything. If I forgot something - Course will add more, I guess.

**Comment by NanakoAC** [comment]
list of buggy items i'm told 
/obj/item/clothing/mask/redscarf 
/obj/item/clothing/mask/gas/death_commando 
/obj/item/clothing/mask/smokable
obj/item/clothing/glasses/hud/broken 
/obj/item/clothing/gloves/lightrig/hacker
/obj/item/clothing/shoes/lightrig 
/obj/item/clothing/under/psyche
/obj/item/clothing/head/collectable
/obj/item/clothing/mask/greenscarf 
/obj/item/clothing/gloves/rig 
/obj/item/clothing/mask/bluescarf

**Comment by Kurgis** [comment]
`/obj/item/clothing/mask/redscarf` `/obj/item/clothing/mask/greenscarf` `/obj/item/clothing/mask/bluescarf`
`//scarves (fit in in mask slot)
//None of these actually have on-mob sprites...`
Scarves do not have on-mob sprites. I believe this may of been the perceived problem.

`/obj/item/clothing/mask/gas/death_commando` cannot find the icon or item states.

`/obj/item/clothing/mask/smokable` should never be spawning, it's solely used as a parent object.

`/obj/item/clothing/glasses/hud/broken` honestly not aware how this works.

`/obj/item/clothing/gloves/lightrig/hacker` `/obj/item/clothing/shoes/lightrig` `/obj/item/clothing/gloves/rig` I'm unable to find how icon_states are handled by RIGs, but they are all present in icons. Are the spawning in as standalone objects?

`/obj/item/clothing/under/psyche` item state and icon state are missing a single character.

`/obj/item/clothing/head/collectable` should never be spawning, another parent object, though kind of useless, and could just be refactored out. Should at least have some kind of icon-state for collectable hats to fallback on at least. Should also be noted that it appears that head items in general do not have a sprite to fallback on, this item should appear invisible.

**Comment by RandomColonist** [comment]
You mentioned pretty much all broken things except beacon which is unobtainable currently and i also want to suggest that old/new guns from piles should have random mags with random quantity of ammo inside them/random quantity if casings and live ammo in case of shotguns, revolvers. Old subtypes of ammo that can explode would be cool too.
