### ISSUE TITLE
Multitools make noise Pulsing, even when Silenced

### ISSUE THREAD

**Issue by Boredone** [discordia-space/CEV-Eris#2991]
If you put an aural dampener on a multitool, it still makes noise when pulsing wires like on an airlock.
As a note, it does actually silence hacking lockers/crates however.

**Comment by NanakoAC** [comment]
mildly annoying to fix since its the wires that theoretically make these noises and the tool doesn't get passed in. a bit of refactoring will be needed to make it work,
