### ISSUE TITLE
Something is causing radio chatter to lag.

### ISSUE THREAD

**Issue by GrayRachnid** [discordia-space/CEV-Eris#3007]
Typing a radio message causes it to take time to go through, meanwhile typing a local message is instant. Unsure what's the cause.

**Comment by Kurgis** [comment]
Depends on how long the bus processor can take the message through, perhaps the delay is intended? Is it acting slower than what was usual?

**Comment by GrayRachnid** [comment]
It'st aking around 30 seconds to a minute and the message you say is delayed as well. As in, after you hit enter while typing a message intended for the radio, your character doesn't even speak until it goes through.

**Comment by NanakoAC** [comment]
this is on master?

**Comment by EvenInDeathIStillServe** [comment]
I believe radio chatter can lag because the telecomms machinery overheated and got damaged. The more damaged they are, the longer it takes for the message to go through. Bug here is that the speech is delayed along with the radio chatter getting broadcasted.
