### ISSUE TITLE
Remains can be found in rubbish piles, but cant be removed - so the pile cant be cleared

### ISSUE THREAD

**Issue by driecg36** [discordia-space/CEV-Eris#3041]
This item isn't interactable with, so it just keeps shifting around in the trash and preventing you from clearing it.

**Comment by driecg36** [comment]
https://i.imgur.com/8BGn7Xr.png this is the item

**Comment by Kurgis** [comment]
This appears to be the relevant line: https://github.com/discordia-space/CEV-Eris/blob/master/code/game/objects/effects/decals/remains.dm

These items are meant as decals, and I don't believe they should ever be spawning in containers.
