### ISSUE TITLE
Проблемы кода одежды

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#305]
Request for Help:: AllahBoom/(Nucky Thompson)(?) (PP) (VV) (SM) (JMP) (CA): Снять наушник через скафандр можно, а обратно надеть - нельзя.

Request for Help:: Destjedor/(Ariana Black)(?) (PP) (VV) (SM) (JMP) (CA): Через ваши стерильные маски можно пить.

**Comment by LethalGhost** [comment]
>Request for Help:: Destjedor/(Ariana Black)(?) (PP) (VV) (SM) (JMP) (CA): Через ваши стерильные маски можно пить.

В чем проблема пить через стерильную маску?

**Comment by SpadesSlick** [comment]
Already fixed.
