### ISSUE TITLE
HIVEMIND | Wires still don't destroy emergency shutters

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3053]
![image](https://user-images.githubusercontent.com/21274357/53695166-23ceff80-3dc9-11e9-9339-0f0615a9186b.png)

**Comment by NanakoAC** [comment]
oh dear

**Comment by soslow4u** [comment]
I was trying to reproduce this issue, but got nothing on current build. https://github.com/discordia-space/CEV-Eris/commit/ddafebb29898d94125ac75f589e26766a696b367
