### ISSUE TITLE
bug: hardsuit module activation (mounted RCD/taser/cannon) is broken, none of the selectable options work

### ISSUE THREAD

**Issue by NanakoAC** [discordia-space/CEV-Eris#3055]
From junkyard, apparently selectable hardsuit modules are broken

test on master branch please, recent clicking bugs may have caused it

**Comment by NanakoAC** [comment]
assigned to rigosex

**Comment by TorinoFermic** [comment]
Bug confirmed at current master at 1e3f5054366154bb3fe906bc50ff45ff9f5b9121

**Comment by soslow4u** [comment]
Fixed in #3271 and #3287
