### ISSUE TITLE
BSD Harpoon will stop working for no discernable reason.

### ISSUE THREAD

**Issue by Pariah919** [discordia-space/CEV-Eris#3077]
The BSD Harpoon will seemingly stop working for no discernable reason for your mob but work for others but still use power.

**Comment by Pariah919** [comment]
UPDATE: Appears to be that interacting with certain machines like ATMs break it and interacting with vending machines will fix it if you have it in your hand.

**Comment by soslow4u** [comment]
Can't reproduce, need more info.

**Comment by soslow4u** [comment]
But Harpoon can't be fired if you click on tables
