### ISSUE TITLE
NeoTheology needs more Litanies

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3116]
- More NT litanies. Sound can affect plants grow IRL, why don’t create few litanies for Agrolyte? Or more litanies for #3112 to make new machinery like #3100 work, as it should. Custodian also needs some litanies, maybe something that can protect him from infections and viruses?

**Comment by driecg36** [comment]
I came up with a few ideas for litanies the other day, I'd like to pitch them here and see if people are interested -

1. Common Litany: Shared Burden - Place your hands on another member of the faith, wait a few seconds, and you transfer around 25% of the damage they have onto yourself. Can't transfer organ damage or the like, just raw damage values.

2. Common Litany: Cant of Protection: Get a very minor toughness buff for the next few minutes.

3. Common Litany: Chant of Faith - Repeatable Litany that recharges the cruciforms of those around you. Minor effect, but the more you chant it the more effective it becomes, to a cap. Can't be spammed, there's a minor cooldown.

4. Priest Litany: Last Words- Lay your hands on someone and delay their death for a few seconds. Makes them conscious if they were unconscious, allows them to speak without stuttering. They die once they utter their last words or a few seconds have passed, so it can't be used as ghetto inaprovaline. Can only be used on people that are in crit or died less than a minute ago.

5. Priest Litany: Chant of War- Another repeatable chant. Grants everyone around you decent toughness and robustness bonuses as long as you are chanting. Functions the same as chant of faith.

6. Inquisitor Litany- Chant of Healing- Another chant. This time, you guessed it, heals everyone you slowly of burn and brute damage.

7. Inquisitor Litany: Chant of Sanctimony- Lowers the robustness and toughness stats of all non-faithful around you, begins to cause pain once you get going.

**Comment by SpadesSlick** [comment]
@driecg36 litanies are not magic, they never act like one. The most mad shit it done is explained by sound waves, and can be blocked by going deaf. Maybe it needed to be fixed in some places, but that's the general idea.

**Comment by driecg36** [comment]
@SpadesSlick I don't see how any of these are any more magical than the ones we have in game. We already have healing litanies, so there's no reason any of these wouldn't work, except maybe last words because it would affect non-neotheologists. That can be easily changed to be just for neotheologists, though. 

 I'd like to know which ones you think are too magical, because I see none that are aside from last words.
