### ISSUE TITLE
Burrows need rework

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3119]
- Burrows and their content should be rebalanced. They should assault civilian sections less, they should have a different sprite (more likely something metal, instead of dirt), and they should be removed by placing a steel on top of them. Dirt effect from burrows opening should be removed, or reworked.

**Comment by ACCount12** [comment]
Making burrows check for light level on the other side and reduce the chance if it's bright there should make inhabited ship section less affected. Replacing current burrows collapsing with just floor tiles would make the whole thing less weird.
