### ISSUE TITLE
Dynamic crosshair

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3120]
Dynamic crosshair to display accuracy instead of screen shaking that can only cause vomit. It should also display enabled safety.

**Comment by SpadesSlick** [comment]
https://www.youtube.com/watch?v=_YhGrugvhHU&t=651s
Here is an example how it works in other 2D game. We need exactly that.

**Comment by SpadesSlick** [comment]
Done by now.
