### ISSUE TITLE
Bounty boards for laborers!

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3125]
- Add a few interlinked "bounty boards" across the ship, maybe even few in maints. Anyone can post a bounty for a small fee (goes either to Ship or Guild account) with title, description, payment agreement and amount of money freelancer will receive. Anyone then can "take" bounty, do it and receive payment upon agreement. Thus, IH can post actual bounties to capture/kill somebody, medical can post bounties for roaches/spiders/other shit they need, science can post bounty for participation in expeditions/science projects or even finding resources for them and basically everything else. This should be done with PDA program, and new job should automatically notify all players.

**Comment by ACCount12** [comment]
Bounty board is now a PDA app, it's even used sometimes.
