### ISSUE TITLE
PDA energy problem

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3126]
- PDAs are running out of power too fast. Honestly they should not do that at all. We need add tesla links in them, or just low yield nuclear cell. Also, PDA shouldn't discarge so quickly, or not discharge at all without using integrated flashlight, or some programms inside it.

**Comment by Regis-Emiel** [comment]
I find the power limitations on tools a bit ridiculous honestly. For all of them. Considering just have scarce cells are, you'd think they would last longer.
