### ISSUE TITLE
Neotheology mass driver issues

### ISSUE THREAD

**Issue by DiscordWizard** [discordia-space/CEV-Eris#3150]
When you place someone in a coffin and then send said coffin into the disposal outlet that shoves it into the mass driver, the coffin only flies until it reaches the tile next to the mass driver, then it stops. To make it worse, when an admin nudged it into place and the mass driver was fired, it simply moved one tile forwards and stayed there.

**Comment by XanderDox** [comment]
This would be because the Mass Driver is placed poorly, and shields/lattices really interfere with it. It needs to face towards the back of the ship rather than into the crevice of the chapel window.
