### ISSUE TITLE
Cease shroom/roach faggotry

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#3154]
![image](https://user-images.githubusercontent.com/9161564/54533268-d2af3600-499a-11e9-9c4c-8605459cc83b.png)

Shrooms are too aggressive in their expansion. Same can actually cab be said about roaches and spiders. Their chance of invading crew area must be lowered, or tied to some sort of storyteller event.

We should not have a hallways full of this shit from the roundstart.

**Comment by TorinoFermic** [comment]
Working on it, it may take time to add features like shoom's spreading being slowed when under light. Burrow not spreading if under light.
