### ISSUE TITLE
Hardsuit magboots oversight

### ISSUE THREAD

**Issue by RandomColonist** [discordia-space/CEV-Eris#3177]
We really need bay hardsuit improvements. For now, magboots can not be worn over regular boots even when attached to a hardsuit, which sucks. Secondly, there is no verb to deploy/undeploy them if they are attached to hardsuit, so you will need to remove hardsuit in order to put on/remove magboots.

**Comment by soslow4u** [comment]
We have code for it there - [/code/modules/clothing/shoes/magboots.dm:pre_equip()](https://github.com/discordia-space/CEV-Eris/blob/master/code/modules/clothing/shoes/magboots.dm#L82), but it does nothing for some reason. Maybe it halts at somewhere at [/code/modules/mob/inventory/equip.dm:equip_to_slot_if_possible()](https://github.com/discordia-space/CEV-Eris/tree/master/code/modules/mob/inventory/equip.dm#L5) check
