### ISSUE TITLE
If people are on fire, the room fills with fire.

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3202]
![image](https://user-images.githubusercontent.com/21274357/54775050-31d0ad00-4c1e-11e9-9643-ae4819229682.png)
And that continues, making more fire! And this almost can't be stopped.

**Comment by soslow4u** [comment]
Not sure if issue, but ZAS feature. Gas contoller processes room, not just tile. So if you had plasma leak somewhere - you would get it all over room
