### ISSUE TITLE
Climbing system is dead

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3204]
Everything needs zero gravity, maybe you should change that magboots-climbing, and wall-climbing do not need zero gravity to climb up. That's weird.

**Comment by ziz11** [comment]
Сode has a 'patch' for such movements atm.

[https://github.com/discordia-space/CEV-Eris/blob/master/code/modules/multiz/ztravel/climb.dm](url)

`if (gravity)
			/*
				Climbing under gravity not yet implemented. would need special powers or augments
			*/
			return FALSE`

**Comment by soslow4u** [comment]
Is fixed in #3267 
![Proof](https://user-images.githubusercontent.com/5019905/55682434-50e57380-596e-11e9-8ed3-97b5f67ab6a2.PNG)
