### ISSUE TITLE
Shining flashlights at wormholes is bad news

### ISSUE THREAD

**Issue by driecg36** [discordia-space/CEV-Eris#3238]
If you shine a flashlight at a wormhole, it'll aggressively spark for a few seconds and presumably teleport the light to the other side. On top of that, it apparently messes with your ability to move - I was unable to move for the rest of the round until someone cryoed me.

**Comment by driecg36** [comment]
https://i.imgur.com/HbjsFEL.png

Light in reference. Standing on the table because climbing onto tables was the only way I could move myself.

**Comment by soslow4u** [comment]
Also, master contoller died in this moment.
