### ISSUE TITLE
New machine pistol dual wielding is semi auto only

### ISSUE THREAD

**Issue by AMM101902** [discordia-space/CEV-Eris#3249]
The new Ironhammer machine pistol "Molly" has a full auto setting, but when dual wielded instead fires semi-automatically. May also affect 3 round burst, but I did not test this.

**Comment by RandomColonist** [comment]
Obviously issue of auto-firing. And you shouldn't be able to dual-wield two machineguns anyway.

**Comment by BlueFishie** [comment]
Issue indeed present when wielding a single FS MP "Molly" as well, not specifically dual wielding. Full-auto setting functions like semi-auto.

**Comment by mistyLuminescence** [comment]
Unable to reproduce as of 14/7/19.
