### ISSUE TITLE
[BUG] Excelsior Implant Removal

### ISSUE THREAD

**Issue by RandomColonist** [discordia-space/CEV-Eris#3308]
Upon removal of the implant, said person is still able to communicate on Excelsior comms and maybe still has antag role.

**Comment by fernandos33** [comment]
i dont really have a problem with thw role being kept. if yiu are a commie its a ideology uou may follow and with a implant or not you will keep following it. (the thing to me is i play doctor a lot. and i MEAN a LOOOT. and everytime i get the implant out. i feel unsure if the guy is still a commie or nah so would  be nice to clarify it

but the comms needs fix indeed

**Comment by SpadesSlick** [comment]
@fernandos33 dude, is this even English you speaking?
