### ISSUE TITLE
Бэйский Бипски плохо себя ведет.

### ISSUE THREAD

**Issue by timmy747** [discordia-space/CEV-Eris#331]
Хотелось бы видеть что-то более ТГ-шное, где хорошо тренированная команда офицеров с Бипски могла арестовывать целые отделы, а не мгновенный вывод из строя оного с помощью обычной биты, минуты раздумий и невозможность положить кого-нибудь на пол с первого удара.

**Comment by SpadesSlick** [comment]
Так же бипский, почти наверняка, не может в этажи. Но на Ребее это вроде как зафиксили, стоит глянуть.

**Comment by Euronem** [comment]
У вас есть десять секунд для подчинения.

**Comment by SpadesSlick** [comment]
Issue will be reformated.
