### ISSUE TITLE
Genetic damage can't be fixed

### ISSUE THREAD

**Issue by Knightfall5** [discordia-space/CEV-Eris#3319]
Genetic damage caused by slimes isn't fixed via Clonex in a cryopod. This leaves people permanently damaged with the only cure being replacing limbs or killing and cloning.

**Comment by fernandos33** [comment]
just use drugs
hyroalin
and ryetalyn
fix it very well and honestly  mixing
ari hyro and rye gives you a potent drug against rads ((i know i may have some typos in tge name of the drugs but... i hope you can understand it))
