### ISSUE TITLE
[BUG] Kill clamp doesn't kills

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#3356]
![image](https://user-images.githubusercontent.com/49165135/56079537-bf0eb800-5dfe-11e9-978a-d4dd1c2dc30d.png)

**Comment by Kurgis** [comment]
Looking through the code comments, this is intentional.

**Comment by Kurgis** [comment]
Also, checking through the Kill Clamp code, it seems to be using an older version of the mecha clamp code. Not sure if that could cause the kill clamp to cause other problems unrelated to this bug report.
