### ISSUE TITLE
[SUGG] Hardsuit mounts

### ISSUE THREAD

**Issue by DeLaFlash** [discordia-space/CEV-Eris#3358]
SUGG: Allow pouches/gloves to be hard mounted on voidsuits just like you can attach air tanks, magnetic boots and helmets to them. Those would be stored inside voidsuit when it is not worn and would deploy into glove/suit slot when one is worn

**Comment by RandomColonist** [comment]
I believe that's niche of RIGsuits already, but for that to happen we need new types of gloves and storages that can only be used with rig, i suppose.
