### ISSUE TITLE
[BUG] Antag objective - steal voidsuit

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#3375]
![image](https://user-images.githubusercontent.com/49165135/56079618-c5516400-5dff-11e9-8754-c4db86505090.png)
Voidsuit is a part of TE advanced RiG, therefore inaccessible by usual means.

**Comment by mistyLuminescence** [comment]
Not an issue as of 14/7/19 - you just need to steal the control module.
