### ISSUE TITLE
[BALANCE] Spears do too much damage

### ISSUE THREAD

**Issue by DeLaFlash** [discordia-space/CEV-Eris#3417]
Bug: Non-Glass Spears are likely unbalanced, being the most damaging melee weapon available currently, even when one-handed.

**Comment by DeLaFlash** [comment]
OVERSIGHT: With new autolathe code it became possible to obtain shards of any material. This lead to creation of spears from diamonds, plasteel and else. Either autolathe or spear crafting needs to be fixed as this is not intended mechanic.

**Comment by RandomColonist** [comment]
#3322
