### ISSUE TITLE
Мысли для HUDа

### ISSUE THREAD

**Issue by EkuDza** [discordia-space/CEV-Eris#342]
Тут я выделяю нужные для себя мысли по поводу новой системы ХУДа. 

- [ ] 1. Пересмотреть систему оверлеев. Доскрестить новую систему и старую.
- [ ] 2. Переделать и дополнить систему анализа положения экрана контейнеров.
- [ ] 3. Переделать New_Hud_Manual.dm. Опять.... 
- [ ] 4. Cделать датум для всех переменных худа у моба
- [ ] 5. Для украшений худа сделать возможность накидывать оверлеи на 1 объект. 
- [ ] 6. Сделать внятный /client/verb/change_ui()(HTML)

**Comment by SpadesSlick** [comment]
No longer relevant.
