### ISSUE TITLE
[BUG] 9mm can not be examined

### ISSUE THREAD

**Issue by DeLaFlash** [discordia-space/CEV-Eris#3425]
Bug: Can't examine the small 9mm pistol
https://cdn.discordapp.com/attachments/375588651599396866/566371786338336801/unknown.png

**Comment by ziz11** [comment]
Can't reproduce bug on current build (master). https://imgur.com/8VZsYBz

Please describe the process of getting this error.

**Comment by soslow4u** [comment]
You would get .command-something.0xffffffff in chat line with this error in log when object would leave your interaction area before you execute some command
Maybe gun was carried away, stored or just destroyed in container before action was clicked in right-click menu.

**Comment by SpadesSlick** [comment]
Not a code issue.
