### ISSUE TITLE
[R&D/Autolathe PR bugs] Pause button is very small

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#3443]
![unknown (2)](https://user-images.githubusercontent.com/21274357/56163886-2df33900-5fd8-11e9-97d8-fbd651d0500c.png)
Can you make it bigger?

**Comment by ACCount12** [comment]
I'm pretty sure it was the same way before it, but yes, more UI improvements are planned. Just not in this PR.
