### ISSUE TITLE
[BUG] HV 7.62 mags in the traitor uplink cannot be used with STS

### ISSUE THREAD

**Issue by AMM101902** [discordia-space/CEV-Eris#3448]
The 30 round High velocity magazines from the traitor uplink no longer fit in the STS, which now only accepts the "civilian" 20 round magazines.

**Comment by shazbot194** [comment]
It looks like we need to add in 7.62 civi mags, and rename the AK mags.
Sorry for the inconvenience.

**Comment by mistyLuminescence** [comment]
Unable to reproduce as of 14/7/19.
