### ISSUE TITLE
[BUG] IH Armory contains 7.62 ammo boxes after Wintermute changed to 5.56

### ISSUE THREAD

**Issue by AMM101902** [discordia-space/CEV-Eris#3460]
No IH weapons currently use 7.62

**Comment by RandomColonist** [comment]
Maybe you'l bother yourself to check before clutter our github with non-actual issues? Fixed from yesterday.
![image](https://i.imgur.com/Gvb42ca.png)

**Comment by RandomColonist** [comment]
Will fix.

**Comment by soslow4u** [comment]
Wasn't it closed already?
