### ISSUE TITLE
[SUGG] Gun Serial Numbers

### ISSUE THREAD

**Issue by Coureere** [discordia-space/CEV-Eris#3501]
My suggestion is to add new feature to the game - gun serial numbers. It will benefit both RP and mechanics, will touch multiple departments and will also add one more feature to forensic.

- Every gun in game, dependant on it origin, will get SHA256 hash serial number (get luck with collision). It will allow players to remember it, write it down or else and track it in future. For example, some dumbass operative lost his gun somehow, but, if Sarge aquired it number some time ago, he will be able to tell later, if the gun confiscated from arrested assistant is the same gun operative lost and etc.
- All FS vendor guns will have first two digits pre-set, so it will always be the same on every giskard, olivav, gladstone or other gun bought from vendor. Same goes for custom vendors which belong to IH or registered on card with IH access - player should be able to set first two digits for any guns loaded in it, but it's not mandatory (can be used for illegal id change).
- All guns that came from guild should be listed on invoice sheet came with guns in crate, so guild will be able (not mandatory) to assist IH if criminal possibly bought a gun from guild.
- All guns from maints will also have serial number, but oldified guns will have some or all digits erased by time or prolonged usage. MAYBE IH should have means of retagging those guns.
- MAYBE give IH easy way to assign serials to guns on paper. As we know, bureaucracy on our build sucks, so it will be nice to have security access requiring program in which you can assign serial number to gun name and owner name (this is for the sake of RP and to ease pain of Inspectors, not mandatory) with possibility to save it as usual document and print it out. Or add pre-set form to existing text files program.
- All guns bought from uplink can be manually assigned any number by buyer or even not to be assigned any number at all (choose "unmarked" option).
- All guns in possession of Serbian Mercenaries should be unmarked.
- MAYBE players should be able to fully or partially erase numbers on their guns by either welding or scratching it with something sharp. It should be hard task with mechanical skill check. Upon failure, you will erase number only partially. Upon critical failure, you will damage the gun, yourself or even break it beyond repair.

Just to conclude, this is NOT MANDATORY. IH can choose to enforce gun registration or not to enforce it. Sarge can beat any operative who not gave him his guns serial numbers or not to do it. Guild can tell IH to fuck off if they request serials from guns they ordered. And etc.

**Comment by RandomColonist** [comment]
Additional idea from discord:
- MAYBE some guns should leave special marking on used casings, for example all IH guns (modern FS guns used by IH) and FS vendor guns for sure, so it will be possible to link casings to particular gun. MAYBE players should be able to adjust that feature on their FS guns as well.
