### ISSUE TITLE
Mechs disappear when crossing z-layer boundry in space

### ISSUE THREAD

**Issue by TYoung86** [discordia-space/CEV-Eris#3515]
Dispite being a space-capable mech, when crossing space z-layer boundries, players are ejected from the mech, and the mech disappears.

**Comment by Kurgis** [comment]
https://github.com/Baystation12/Baystation12/pull/25392
This may be related.

**Comment by TYoung86** [comment]
Not fixed if master is what's on the server; just experienced it again

**Comment by ACCount12** [comment]
Master is not on server yet.
