### ISSUE TITLE
[OVERSIGHT/SUGG] Replace Abandonment with Jump

### ISSUE THREAD

**Issue by Coureere** [discordia-space/CEV-Eris#3533]
It appears that our code fully supports bluespace jump, has messages set and even mentioned in evacuation code, but evacuation controller simply doesn't have options for jump defined.

Abandonment should be replaced with Jump in every place excluding keycard auth device for obvious reason. Got tired of retards yelling at comms "REEEEE I AM BORED ABANDON SHIP" and vote initiating full ship abandonment for no real reason, this is just immersion-breaking and makes no sense. Bay-like jump will make perfect sense as round-ender instead.

**Comment by zamolxius** [comment]
based.  And red-pilled.

**Comment by AncientV25** [comment]
Replace doesn't need to be done, re-adding bluespace jump is trivial since what Nanako did is in github history
