### ISSUE TITLE
[BUG] Sell() Proc Only Calls One (1) Time

### ISSUE THREAD

**Issue by granodd** [discordia-space/CEV-Eris#3554]
Selling things on the cargo shuttle only works one time before the Sell() proc stops properly working. In a controlled test of one crate with five sheets of plasma, the first was sold and credits were earned, but attempting to sell the second crate yielded no change in credits to the Guild account, and (likely) no change in the cargo history of items sold.

This can be recreated easily on the live server by selling anything, and then attempting to sell anything afterwards. The cargo history screen being stuck on the first ever shipment you sold.

**Comment by fernandos33** [comment]
the runtime error it gives out is 
Runtime in supply.dm,66: Cannot execute null.total printout().
  proc name: sell (/datum/controller/subsystem/supply/proc/sell)
  src: Supply (/datum/controller/subsystem/supply)
  call stack:
  Supply (/datum/controller/subsystem/supply): sell()
  Supply Shuttle (/datum/shuttle/autodock/ferry/supply/drone): short jump(Centcom (96,172) (/obj/effect/shuttle_landmark/supply/centcom))
