### ISSUE TITLE
Allow players to visually identify both open space and flooring on above z-level.

### ISSUE THREAD

**Issue by Kurgis** [discordia-space/CEV-Eris#3607]
Every tile should already register what is above it for other calculations (moving up and down), when you use a "Look Up" command, it will place an overlay in every turf which has ceiling above it. So you can visually identify every turf with something above it, or has open space.

This is the closest found example which showcases something close to this: https://github.com/ParadiseSS13/Paradise/pull/4411

That was a meme PR, and serves no real functionality in Paradise, but would function similarly to how I envision it. You use a "Look Up" command, and it will then reveal that overlay, press it again, the overlay is no longer shown. This could open up a new line of gameplay as well, as mobs could be placed with the same checks as the overlay (like spiders crawling on the ceiling), that'd otherwise would be unseen without looking up.

**Comment by RandomColonist** [comment]
Also will require placing corresponding to this verb button on the UI. It can replace aiming button which we no longer have. I believe that finding this button (without macross) somewhat disorienting each time, especially if you need to use it urgent.
