### ISSUE TITLE
Burrows cause atmospheric pipes to detach into fittings when they share the same turf after game-start.

### ISSUE THREAD

**Issue by Kurgis** [discordia-space/CEV-Eris#3613]
In a recent round the Supermatter was delaminated by a burrow. It spawned under one of the coolant pipes, causing it to detach, the Supermatter would eventually fill with gas it wouldn't remove. It went unnoticed, and when it was, it was too late. This caused the round to end, because an unnoticed burrow blew a hole into Engineering.

Additionally, there are various areas all over the ship which do not get proper atmospheric regulation, all because they've become disconnected in various places. Sometimes this even occurs outside the confines of the ship, requiring EVA to fix.

**Comment by SpadesSlick** [comment]
test
