### ISSUE TITLE
Музыка в лобби ломается

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#362]
Если ты закончил раунд в коридоре, где звуки изменяются ради эффекта "эхо", или нажал респавн там, то музыка в лобби будет звучать с такими же эффектами. А это больно.

**Comment by SpadesSlick** [comment]
Такая же проблема возникает, когда включают педальную музыку, а ты в коридоре, где она искажается. По хорошему надо музыку отделить отдельно, без искажений.

**Comment by SpadesSlick** [comment]
Было решено убить само эхо по ряду других причин.

**Comment by bo20202** [comment]
:joy: :ok_hand::skin-tone-2:

**Comment by SpadesSlick** [comment]
Было решено вернуть вернуть эхо по ряду причин.

**Comment by SpadesSlick** [comment]
oh just fuck it
