### ISSUE TITLE
[OVERSIGHT?] Blank autolathe disks lack space for cloning

### ISSUE THREAD

**Issue by Hatterhat** [discordia-space/CEV-Eris#3621]
EDIT: figured out a workaround, advanced data disks from R&D have 256 GQ, they're under mesons.

https://github.com/discordia-space/CEV-Eris/blob/master/code/game/objects/items/weapons/autolathe_disks.dm#L21

This code that trims down disks to only have enough space for their designs prevents autolathe disk cloners from copying all the designs from a source disk to a blank disk by limiting them to 64 GQ when blank, while other disks are larger.

**Comment by ACCount12** [comment]
Yeah, that was intended. You figured it out right.
