### ISSUE TITLE
The way gun icons are handled needs to be refactored

### ISSUE THREAD

**Issue by Kurgis** [discordia-space/CEV-Eris#3654]
![BadIcons](https://user-images.githubusercontent.com/35203040/62020998-39d3c700-b193-11e9-88e5-1150b80e04d2.png)
For a single weapon, the required amount of icons multiplies for each "moving part" it has.

![GoodExample](https://user-images.githubusercontent.com/35203040/62021190-09d8f380-b194-11e9-9acb-d5ffb5d0965e.png)
Instead they should all be separated, and then added onto each other by the code.

In fact it should be taken even further, such as something here:
![z12r](https://user-images.githubusercontent.com/35203040/62021709-94baed80-b196-11e9-8c09-67b1afa2ca2e.png)

**Comment by TorinoFermic** [comment]
For the good fix to occur, the new code requires to take advantage of overlays.
