### ISSUE TITLE
Radio announcements

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#366]
Remove announcements as they are and remake the as radio-messages. Also, it would be nice to actually voice them.

- [x] Move everything to radio
- [ ] Voice the messages

**Comment by SpadesSlick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Система оповещений](https://trello.com/c/gZ1SwZiG/22--)

**Comment by SpadesSlick** [comment]
И аноунсы о прибытии, и эти старые-новые аноунсы нужно запихать в имя "CEV Eris System Announcer". При воспроизведении звука аноунса нужно сделать проверку, слышит ли моб сам аноунс по рации. Звуки пока стоит использовать старые, те женские голосовые сообщения.

**Comment by fluorescent-net** [comment]
На такие уведомления хорошо бы еще звук повесить, что-нибудь вроде короткой мелодии (как в метро/тц). На алерты можно и звук баззера.
