### ISSUE TITLE
Early warning system

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#367]
Детектить только некоторые специфические рандомивенты (метеориты, приближение нло, штормы etc.) с работающим радаром. Естественно, все эти модули/машинерию для оповещений сделать ломаемыми и отключаемыми.

Требуются спрайты, продуманный механ сборки и настройки, а так же размещение на карту с созданием отсека.
- [ ] Спрайты самой машинерии.
- [ ] Механ сборки и настройки.
- [ ] Размещение на карте.

**Comment by SpadesSlick** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Система оповещений](https://trello.com/c/gZ1SwZiG/22--)

**Comment by fluorescent-net** [comment]
>размещение на карту

Мостик кажется вполне подходящим местом. Хотя можно добавить больше функциональности почти не используемому отсеку с телекомами. Сами датчики/радары/whatever в идеале бы вынести за обшивку, на мой взгляд.

**Comment by SpadesSlick** [comment]
Значительная часть подобного оборудования находится в ижненерке, и настраивать это будут так же инженеры. Да и впихнуть туда будет проще.

**Comment by Voldirs** [comment]
Not viable with overmap introduction
