### ISSUE TITLE
Сломаные превью персонажей

### ISSUE THREAD

**Issue by MyLittleLoly** [discordia-space/CEV-Eris#370]
Большая часть одежды на превью, в меню создания персонажа, сломана.
- [x] Спрайты глаз в превью слетели.
- [x] Вероятно в записях персонажей тоже.
- [ ] Часть одежды не отображается.
![image](https://cloud.githubusercontent.com/assets/3694552/21964312/ca4dad9e-db5a-11e6-990b-3f3751237288.png) ![image](https://cloud.githubusercontent.com/assets/3694552/21964319/d44af004-db5a-11e6-8e92-104c2891949f.png) ![image](https://cloud.githubusercontent.com/assets/3694552/21964327/e5677cae-db5a-11e6-8cf9-724b7a35ad2e.png)

**Comment by SpadesSlick** [comment]
Скорее всего это связано с #390.

**Comment by SpadesSlick** [comment]
No longer actual.
