### ISSUE TITLE
AI has some some ridicilous mob traits

### ISSUE THREAD

**Issue by MyLittleLoly** [discordia-space/CEV-Eris#374]
LunarDarkness/(S.T.E.L.L.A.R.I.S.): ЕСЛИ ИИ ТЫКАЕТ НА ЛЕСТНИЦУ. ОН ТЕЛЕПОРТИРУЕТСЯ
LunarDarkness/(S.T.E.L.L.A.R.I.S.): Ядром

LunarDarkness/(S.T.E.L.L.A.R.I.S.):  ИИ может проверять пульс.
LunarDarkness/(S.T.E.L.L.A.R.I.S.): У мобов.

AI can use ladders and check pulse. Probably it can do some other funny shit too.

**Comment by LethalGhost** [comment]
Скорее всего
ии может доставать под себя батарейку из бура, 
вырывать из людей застрявшие в них предметы, 
при стрельбе в ИИ и прочих есть логи о выстреле в определенную часть тела.

**Comment by MrFoxik** [comment]
Fixed
