### ISSUE TITLE
Toxins

### ISSUE THREAD

**Issue by rpilcrow** [discordia-space/CEV-Eris#3809]
Alright, where do I begin?
First off, https://github.com/discordia-space/CEV-Eris/blob/f7aa28fd4b4d0386c3393d829681ebca526f1d2d/code/modules/mob/living/carbon/human/human_damage.dm
Lines 214 to 263, last changed by @ITCups for #3697 

For the laymen, this code block alters adjustToxLoss() to do the following things:
1. Toxins damage bypasses the toxloss var and is now dealt directly to the organs.
2. The order for this is liver > kidneys >anything > brain
3. Because the toxloss var is never set, this damage will only show up in the body scanner as organ damage. Health scanners and medibots will not recognise it.
4. Because this affects organs directly and simply replaces the functionality of adjustToxLoss(), this allows chemicals that previously cured toxloss to instead cure organ damage.
5. You can cure all organ damage, and by extension braindamage with antitoxin/dylovene.
6. You can cure braindamage with antitoxin.
7. _You can cure braindamage with antitoxin._

Second, spiders.
1. Spiders now inject a toxin called 'Pararein', introduced in the same PR.
2. Pararein is a strength 1 toxin, which makes it 20 times stronger than standard 'Toxin' and 3 times stronger than Plasma.
3. Roughly one unit of Pararein is sufficient to destroy your liver.
4. Incidentally, roughly one unit of Plasma is sufficient to deal around 35 damage to your liver, which can take 60 damage at max.
5. Once your liver is destroyed, it deals damage to your kidneys, organs, and finally brain - if it hasn't succumbed to the miscellaneous effects of your other organs being destroyed.
6. Pararein has 10 addiction chance. You can become addicted to a poison.

There's almost certainly a whole lot more to consider here, including other sources of toxloss such as radiation. Chances are this is just the surface of it.

**Comment by ITCups** [comment]
Ah, i didn't consider adjustToxLoss() being used to treat toxin damage.
Anyway those changes were made to migrate to somewhat organ oriented medicine.
And since all toxins has very slow metabolism to accumulate this damage it will take a while.
This will probably require some tweaking.

**Comment by ACCount12** [comment]
That's some excellent bug reporting right here. Wish I looked here before spending my time on figuring out this mess.
