### ISSUE TITLE
Harpoon + bear trap = soft lock

### ISSUE THREAD

**Issue by Trilbyspaceclone** [discordia-space/CEV-Eris#3812]
Get a bluespace harpoon and a bear trap, not the weak ones that brake.
Set the trap and force/wait for someone to walk onto it.
Use the "receiving" mode on the bear trap once it has activated at lest 2 tiles away from said trapped person
Laugh as they are not unable to free themselves without a harpoon of their own.

**Comment by Trilbyspaceclone** [comment]
this was fixed

**Comment by SpadesSlick** [comment]
Was reported on a live server after fix.

**Comment by Garen7** [comment]
I found the fix, I’m at work right now though so I’ll fix it later

**Comment by Garen7** [comment]
So I tested this and I can't reproduce it, bluespace harpoons cannot teleport anchored objects and whenever you buckle a mob to an anchored object the mob also becomes anchored. The bear trap becomes anchored when you arm it and buckles a mob when triggered. This makes it impossible to teleport a mob who is in a bear trap. This is what #3820 said it does, is there any more context to how this occurred on a live server?

**Comment by Kurgis** [comment]
There was changes to how bear traps operate after the creation of this issue, may of changed behavior.

**Comment by SpadesSlick** [comment]
Tested to be not a thing anymore.
