### ISSUE TITLE
If you aim and get flashbanged you cant leave zoomed screen

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#3847]
Self explanatory

**Comment by hyperioo** [comment]
I've just tested it with the grenade launcher scope. Being flashed turns your screen white, put you on the ground and automatically unzoom your screen.

Were there any special circumstances @infraredbaron ? If not can be closed I think, someone may have fixed that.

**Comment by hyperioo** [comment]
Likely fixed. Will reopen if it happens again.
