### ISSUE TITLE
Seed vendor issues & tobacco

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#3850]
Tobacco seeds have no sprite
tobacco seed packets don't even function
The garden has a /vending/hydroseeds vendor for seeds but not a seed_storage machine. The vendor is missing seeds that would only be acquirable from the seed_storage such as tobacco seeds. IMO they should get a vendor and seed storage, with the seed storage being empty instead of full.

**Comment by hyperioo** [comment]
Tobacco seeds still have no sprites and don't function (_The packet seems to be empty. You throw it away._)
There is now an empty seed storage for hydroponics. Missing seeds (those in the full version of the seed storage) still need to be added to the seed vendor.
