### ISSUE TITLE
The "." prefix doesn't work for radios anymore

### ISSUE THREAD

**Issue by mattroks101** [discordia-space/CEV-Eris#3917]
Only `:` seems to work. I can no longer type `.h` to use my department radio. Possible related to https://github.com/discordia-space/CEV-Eris/pull/3832.

**Comment by seekin4u** [comment]
![image](https://user-images.githubusercontent.com/24856443/86930732-012cc380-c140-11ea-9033-f58df32c6ff7.png)
It is now chosen in your prefs. "single special character".
