### ISSUE TITLE
Rework /obj/item/weapon/tool_upgrade/productivity/red_paint

### ISSUE THREAD

**Issue by ITCups** [discordia-space/CEV-Eris#3938]
instead of an item `/obj/item/weapon/tool_upgrade/productivity/red_paint`
tools should be upgradable using actual red paint reagent
`/obj/item/weapon/tool_upgrade/productivity/red_paint`
doesnt even have red paint in it

**Comment by ACCount12** [comment]
Down the SUGG drain it goes.
