### ISSUE TITLE
Oversight: Preachers armor has no bio protection

### ISSUE THREAD

**Issue by robosperg** [discordia-space/CEV-Eris#3951]
Preacher's coat (both variants)
1: "melee" -> 15
2: "bullet" -> 15
3: "energy" -> 15
4: "bomb" -> 0
5: "bio" -> 0
6: "rad" -> 0

Literally all other NT, both armors and helmets:
1: "melee" -> 35
2: "bullet" -> 20
3: "energy" -> 20
4: "bomb" -> 25
5: "bio" -> 100
6: "rad" -> 80

https://discordapp.com/channels/255035529085583360/375588651599396866/631801521918705664

**Comment by MacBlaze1** [comment]
Pretty sure intended.

**Comment by hyperioo** [comment]
NT coat stats are now:

> melee = 30,
> bullet = 20,
> energy = 20,
> bomb = 0,
> bio = 0,
> rad = 0

As  MacBlaze1 said, pretty sure it's intended. It's a coat, not an air-tight suit like the one of the NT custodian. It should not protect against biohazard nor radiations. Can be closed I guess.
