### ISSUE TITLE
BUG? Burrows can grow in NT places

### ISSUE THREAD

**Issue by robosperg** [discordia-space/CEV-Eris#3954]
OVERSIGHT/BUG: Burrows and fungi can grow in NT places (actually, it might be in the small blindspots the obelisks don't reach, if it IS that, ignore this)

https://discordapp.com/channels/255035529085583360/375588651599396866/632327846399836200

**Comment by hyperioo** [comment]
Already a check to avoid spawning burrows near active obelisks.
In burrows.dm:
```
var/obj/machinery/power/nt_obelisk/obelisk = locate(/obj/machinery/power/nt_obelisk) in range(7, src)
if(obelisk && obelisk.active)
	qdel(src)
	return
```
