### ISSUE TITLE
Оверлей сварки не работает

### ISSUE THREAD

**Issue by ucnaHez** [discordia-space/CEV-Eris#396]
Развариваю стену без очков - все разваривается, пишется, что, мол, глазам больно - а эффекта, как от флеша - нету.

**Comment by EkuDza** [comment]
Бейцовский оверлей был какой-то адской смесью из кучи нарезанных объектов, так что я его снес нахер пока что, буду свое пилить.

**Comment by SpadesSlick** [comment]
Done.
