### ISSUE TITLE
SUGG/Oversight: Lockers clog dispsosals

### ISSUE THREAD

**Issue by robosperg** [discordia-space/CEV-Eris#3972]
dunno if anyone cares but seems griffy/annoying enough to take note of
https://discordapp.com/channels/255035529085583360/375588651599396866/632737551878193162
https://discordapp.com/channels/255035529085583360/375588651599396866/632748777299640321
https://discordapp.com/channels/255035529085583360/375588651599396866/632748941896843265

**Comment by ACCount12** [comment]
No longer happens unless the locker is ID locked. Sorter machines try to open closets otherwise.
