### ISSUE TITLE
Massively replace interfaces to NanoUI where it has not already been done.

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#405]
- [ ] [/obj/machinery/computer/aifixer](https://cloud.githubusercontent.com/assets/9161564/22077061/b0be5ae8-ddc3-11e6-88b5-b598e3b67f2a.png) 

- [ ] [/obj/machinery/computer/mecha](https://cloud.githubusercontent.com/assets/9161564/22077091/cce21c8c-ddc3-11e6-941b-5eb6f00c413c.png)

- [ ]  [/obj/machinery/computer/general_air_control](https://cloud.githubusercontent.com/assets/9161564/22077132/f5747438-ddc3-11e6-9fae-93ae90c15a62.png)

- [ ]  [/obj/structure/dispenser](https://cloud.githubusercontent.com/assets/9161564/22077164/13798aa4-ddc4-11e6-82d8-3c22bda00439.png)

- [ ] [/obj/machinery/computer/operating](https://cloud.githubusercontent.com/assets/9161564/22077570/b787eb4e-ddc5-11e6-9fc7-53872a958e50.png)

- [ ] [/obj/machinery/firealarm](https://cloud.githubusercontent.com/assets/9161564/22077596/d70cc912-ddc5-11e6-9e63-8aeaf983ffde.png)

- [ ] [/obj/machinery/body_scanconsole](https://cloud.githubusercontent.com/assets/9161564/22077824/da80b7ba-ddc6-11e6-82f9-69fd93289a4c.png)

- [ ] [/obj/machinery/disposal](https://cloud.githubusercontent.com/assets/9161564/22077894/1c6bf0e0-ddc7-11e6-8a50-04f4b5a69e62.png)

- [ ] [/obj/machinery/computer/med_data](https://cloud.githubusercontent.com/assets/9161564/22077941/4c1d6ef4-ddc7-11e6-90ec-7b2b44cfb16e.png)

- [ ] [/obj/machinery/computer/secure_data](https://cloud.githubusercontent.com/assets/9161564/22078499/2e9392ee-ddc9-11e6-858e-14f77f80282e.png)

- [ ] [/obj/machinery/computer/cloning](https://cloud.githubusercontent.com/assets/9161564/22077963/6aef29ee-ddc7-11e6-8ffd-ea2f96b1e24c.png)

- [ ] [/obj/machinery/keycard_auth](https://cloud.githubusercontent.com/assets/9161564/22078032/a99442ec-ddc7-11e6-83a7-b38094b01572.png)

- [ ] [/obj/machinery/chem_master](https://cloud.githubusercontent.com/assets/9161564/22078126/0fd16af8-ddc8-11e6-8c4c-c03db5afa911.png)

- [ ] [/obj/machinery/reagentgrinder](https://cloud.githubusercontent.com/assets/9161564/22078151/2c1eddc6-ddc8-11e6-9fca-182d2f1070a7.png)

- [ ] [/obj/machinery/computer/curer](https://cloud.githubusercontent.com/assets/9161564/22078260/7ae416d8-ddc8-11e6-9036-e8f5a48eec03.png)

- [ ] [/obj/machinery/computer/arcade/battle ](https://cloud.githubusercontent.com/assets/9161564/22078373/d437f132-ddc8-11e6-975c-c877a64a972c.png)

- [ ] [/obj/machinery/autolathe](https://cloud.githubusercontent.com/assets/9161564/22078532/59d7b35e-ddc9-11e6-9701-36388973a0a5.png)

- [ ] [/obj/machinery/computer/communications](https://cloud.githubusercontent.com/assets/9161564/22079000/494181da-ddcb-11e6-980c-cc07f0f33095.png)

- [ ] [/obj/machinery/computer/supplycomp](https://cloud.githubusercontent.com/assets/9161564/22079072/9d44170c-ddcb-11e6-97fa-c876252de48b.png)

- [ ] [/obj/machinery/computer/ordercomp](https://cloud.githubusercontent.com/assets/9161564/22079216/14250f7a-ddcc-11e6-9f3c-7314f9a534fc.png)

- [ ] [/obj/item/device/destTagger](https://cloud.githubusercontent.com/assets/9161564/22079264/3fd1d43c-ddcc-11e6-8c7c-a80b5620ef7b.png)

- [x] [/obj/machinery/biogenerator](https://cloud.githubusercontent.com/assets/9161564/22079358/9e9a22a8-ddcc-11e6-84be-6ae20a9cbfbb.png)

- [ ] [/obj/machinery/computer/drone_control](https://cloud.githubusercontent.com/assets/9161564/22079546/59bf9586-ddcd-11e6-9944-ddaf8e014f68.png)

- [ ] [/mob/living/bot/medbot](https://cloud.githubusercontent.com/assets/9161564/22544824/7179ce82-e947-11e6-8faf-7ac1b8c1728a.png)

- [ ] [/mob/living/bot/floorbot](https://cloud.githubusercontent.com/assets/9161564/22544853/94e7e3ea-e947-11e6-9dc7-657345298f8a.png)

- [ ] [/mob/living/bot/farmbot](https://cloud.githubusercontent.com/assets/9161564/22544953/e791820e-e947-11e6-99bc-d297b3d45b6c.png)

- [ ] [/mob/living/bot/secbot](https://cloud.githubusercontent.com/assets/9161564/22544991/13baf284-e948-11e6-825c-7fe277ec25ea.png)

- [ ] [/mob/living/bot/cleanbot](https://cloud.githubusercontent.com/assets/9161564/22545047/47ec6830-e948-11e6-9586-675b0f5587d6.png)

# R&D

- [ ] [/obj/machinery/computer/rdservercontrol ](https://cloud.githubusercontent.com/assets/9161564/22077446/48abda3c-ddc5-11e6-8024-497f0fe6b97c.png)

- [ ] [/obj/machinery/computer/rdconsole/core ](https://cloud.githubusercontent.com/assets/9161564/22077489/712a93c2-ddc5-11e6-8c9c-28fe7440335d.png)

- [ ] [obj/machinery/computer/rdconsole/robotics](https://cloud.githubusercontent.com/assets/9161564/22077535/97e1371e-ddc5-11e6-82bc-5dd9be3a5c94.png)

- [ ] [/obj/machinery/artifact_harvester](https://cloud.githubusercontent.com/assets/9161564/22077722/65db1c34-ddc6-11e6-84a5-9d418bc2a80f.png)

# Telecoms

- [ ] [/obj/machinery/computer/message_monitor](https://cloud.githubusercontent.com/assets/9161564/22077266/823d129e-ddc4-11e6-81ec-da3851bcb1af.png)

- [ ] [/obj/machinery/computer/telecomms/monitor](https://cloud.githubusercontent.com/assets/9161564/22078589/918b411c-ddc9-11e6-9a5a-d2790df56783.png)

- [ ] [/obj/machinery/computer/telecomms/traffic](https://cloud.githubusercontent.com/assets/9161564/22078617/ac84e7b6-ddc9-11e6-8570-dc4ff0eedb8d.png)

- [ ] [/obj/machinery/computer/telecomms/server](https://cloud.githubusercontent.com/assets/9161564/22078645/c856f2ea-ddc9-11e6-9608-5e6288ade955.png)

- [ ] [/obj/machinery/telecomms/hub](https://cloud.githubusercontent.com/assets/9161564/22078724/1b879f5a-ddca-11e6-8908-c036937897ab.png)

- [ ] [/obj/machinery/telecomms/receiver](https://cloud.githubusercontent.com/assets/9161564/22078758/3906d424-ddca-11e6-9356-0833a990d8c9.png)

- [ ] [/obj/machinery/telecomms/broadcaster](https://cloud.githubusercontent.com/assets/9161564/22078798/6263230e-ddca-11e6-9215-962b1484817c.png)

- [ ] [/obj/machinery/telecomms/processor/](https://cloud.githubusercontent.com/assets/9161564/22078844/91fb4f7e-ddca-11e6-9c5a-3dd0c0d25e62.png)

- [ ] [/obj/machinery/telecomms/bus](https://cloud.githubusercontent.com/assets/9161564/22078912/d6fd5446-ddca-11e6-99de-f2804fbdbcad.png)

- [ ] [/obj/machinery/telecomms/relay](https://cloud.githubusercontent.com/assets/9161564/22078925/f25776c2-ddca-11e6-80a6-d0f8c5181012.png)

- [ ] [/obj/machinery/telecomms/server](https://cloud.githubusercontent.com/assets/9161564/22078955/0ec8b118-ddcb-11e6-836d-e8c9c19115bf.png)

**Comment by SpadesSlick** [comment]
Обновил клинботами и прочими штуками.

**Comment by SpadesSlick** [comment]
Updated to english.

**Comment by NanakoAC** [comment]
well that's the task of a lifetime.

I don't think there's any point in just porting things, the functional gain is very small for the work involved.

But if any of these devices is getting overhauled for some other reason, they should be ported to nano as part of that process
