### ISSUE TITLE
[BUG] [Ancient] Footprints are random

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#4050]
Bloody footprints now appear facing a random direction, even if you walk in a straight line
![unknown](https://user-images.githubusercontent.com/49165135/67633985-6943be00-f8bf-11e9-86fc-87dcf56cccc2.png)

**Comment by Garen7** [comment]
https://github.com/tgstation/tgstation/pull/45752

Could be related
