### ISSUE TITLE
[BUG][Balance] Human shields are OP

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#4052]
Human shields need a hard nerf, it blocks 100% of damage you would take. I have survived 30 gunshots, 3 grenades point blank and a E-sword thanks to using some poor sod as a human shield

**Comment by AlexMorgan3817** [comment]
Maybe add bullet penetration?

**Comment by MacBlaze1** [comment]
SUGGESTION / BALANCE ALREADY FIXED
