### ISSUE TITLE
[BUG] Everytime if u click on grinder it will show u huds of interactions

### ISSUE THREAD

**Issue by AlexMorgan3817** [discordia-space/CEV-Eris#4070]
I was want to put beaker in, and after putting i saw huds
![image](https://user-images.githubusercontent.com/46600554/67638416-b606b380-f916-11e9-907e-5ddbca24fb1c.png)

**Comment by runecap** [comment]
This isn't a bug, you're meant to pick from the hud.

**Comment by AlexMorgan3817** [comment]
> This isn't a bug, you're meant to pick from the hud.

@runecap, beaker putting in, and hud opening -_-

**Comment by MacBlaze1** [comment]
Already fixed.
