### ISSUE TITLE
Port special roles' results in a separate window like Tau.

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#408]
They have it popping up in a separate window after round end. There are some other round stats, but we don't have them and we shouldn't temper with them.
![image](https://cloud.githubusercontent.com/assets/9161564/22018265/1224d8ee-dcbf-11e6-83b7-217e0bba20a4.png)
I assume, they have it ported from VG.

https://github.com/TauCetiStation/TauCetiClassic

**Comment by SpadesSlick** [comment]
А титры вообще нужны?

**Comment by fluorescent-net** [comment]
Настройку я запилил, потому что меня титры только из себя выводили.

Можно вместо них так же просто антагов выдавать.

**Comment by MyLittleLoly** [comment]
Вполне можно впилить титры с проигрыванием космозасранца, с настройкой в преференсах.

**Comment by SpadesSlick** [comment]
Плохая идея, особенно с космозасранцем. Это было глупо, крутить песню для эпичных моментов в конце КАЖДОГО раунда, а не юзать ее только тогда, когда это нужно.

Достаточно просто добавить в это окно законы ИИ и спецролей, этого хватит.

**Comment by fluorescent-net** [comment]
https://github.com/animusdev/green/commit/ce1630ab3e283431ae0821511d752da071d5d8d5
