### ISSUE TITLE
[BUG] [Major] Mesons and radsuit does not protect from SM

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#4165]
Radsuit and meson goggles (on) didnt protect from the radiation emitted by the SM

**Comment by MadmanMartian** [comment]
Unable to reproduce: Suited up in a full radsuit, was unaffected by radiation.

to_chat(world, "rads: [effect] rad_protection: [rad_protection], result: [max((1 - rad_protection) * effect, 0)]")

![image](https://user-images.githubusercontent.com/30557196/69697040-6d8b1300-10d9-11ea-823d-7897443dc248.png)
