### ISSUE TITLE
[BUG] [MAJOR][Balance]

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#4173]
incurable spider venom, regardless of dialysis it stays forever leading to a whole round of passing out
TL;DR
Nerf sophoric and parapelin

**Comment by Garen7** [comment]
Should be fixed by #4207

**Comment by MadmanMartian** [comment]
Looks to be that it adds the reagent each attack.

Maybe have a cap on how much it injects?

**Comment by Garen7** [comment]
#4207 made it so anti toxin remover spider toxin and I haven’t seen any issues with it currently so I’m pretty sure this isn’t an issue anymore
