### ISSUE TITLE
[BUG] Excelsior implants don't turn implantees into excelsior members when implanted.

### ISSUE THREAD

**Issue by GoodG1448** [discordia-space/CEV-Eris#4301]
Found out about this issue on Sunday:

Steps:

1- Either admin spawn excelsior complaint implants or make them in a reconstruction machine
2- Spawn a carbon/human
3- Implant them in the head
4- Scan them with a body scanner to check if the implant is inside
5- Either possess the human you just implanted or aghost and turn antagHUD on.
6- See as they have the implant inside them but don't get converted to excelsior

I was wondering why people I implanted weren't talking into excel comms that round. Turned out that they weren't even excelsior members despite me emptying a full rubber mag on their heads and implanting them.

**Comment by MadmanMartian** [comment]
The human would not have a mind until you possess it, so it would fail certain checks.

It should really tell you you can't even try to implant that person. Was this an excelsior leader implant?

**Comment by GoodG1448** [comment]
They were complaint implants gotten from the excel implant reconstructor. Excelsior leader implants are only given to storyteller-created Excelsior members and are only accessible to regular players if removed by surgery (which kills the implanted person.)
