### ISSUE TITLE
[BUG] Flipped tables don't do shit to block bullets/energy shots

### ISSUE THREAD

**Issue by GoodG1448** [discordia-space/CEV-Eris#4305]
All types of tables don't do shit to block bullets, fliped tables are useless for that matter.

![wew](https://user-images.githubusercontent.com/38330373/69765335-39a00400-1152-11ea-9494-7bc1b2af27a3.png)
![wewlad](https://user-images.githubusercontent.com/38330373/69765339-3d338b00-1152-11ea-9f60-934848dfcc90.png)

**Comment by Boredone** [comment]
It looks like (Currently) flipped tables only help if you are ON the same tile as the flipped table. 40% it hits the table instead.
While if it's unflipped, if you are directly behind it (as far as the shooter is concerned), you have a 20% chance for the table to block it, 40% if you are laying down.

If relevant, only tested this with straight shots, no diagonals.
Overall not very reliable currently, and most tables arn't able to take more then a few shots.

**Comment by Trilbyspaceclone** [comment]
As Boredone states, it goes give you odds of block well ON the same tile. Once flipped the table your ment to walk down onto the same tile
