### ISSUE TITLE
Protolathe cannot use Silicon properly

### ISSUE THREAD

**Issue by cruxxansata** [discordia-space/CEV-Eris#4352]
While the protolathe can accept a beaker, and that beaker may be filled with silicon, and the computer will tell you there is silicon, _you still cannot build things that require silicon._

This was the case before the protolathe was parented under the autolathe and it is still a problem. I tried to pour silicon inside of it now to see if it was still an issue, and it accepted the beaker itself and reports the presence of silicon in the materials listing. However, not only can I not make use of the silicon, it will also not allow me to eject the beaker.

Anything requiring silicon (modular computers in particular) cannot be built, unless there is something I am missing.

![image](https://user-images.githubusercontent.com/13389337/69919649-e88b5b00-1444-11ea-87c0-69c7b71cf403.png)

**Comment by Doloreere** [comment]
https://github.com/Doloreere/CEV-Eris/commit/5617dd3808a858276df3ffa9f7b88ddd3e9e75e1

**Comment by cruxxansata** [comment]
It was pointed out to me on the discord later that the beaker can be removed.

Also, didn't a recent change fix this issue?

**Comment by ACCount12** [comment]
Was fixed by #4364

**Comment by Garen7** [comment]
unpin please
