### ISSUE TITLE
[BUG] Copyright protected disk contents can be copied

### ISSUE THREAD

**Issue by infraredbaron** [discordia-space/CEV-Eris#4517]
Using file manager you can upload design files effortlessly to your hard disc, despite copyright protection.
![image](https://user-images.githubusercontent.com/49165135/72564803-42db6080-38b9-11ea-96fe-65690dc7c1a7.png)

**Comment by ACCount12** [comment]
Good, you _copied_ it. Now upload it to another disk and try using that copy disk in a lathe.
