### ISSUE TITLE
Cyrillic problems with capital letters (513)

### ISSUE THREAD

**Issue by WalkmanNik** [discordia-space/CEV-Eris#4669]
Capital letters incorrectly displayed in cyrillic after 513
![1](https://user-images.githubusercontent.com/13059199/75568251-7f3bd800-5a85-11ea-98e3-25713106d6af.png)
На кириллице неправильно отображаются заглавные буквы после перехода на 513

**Comment by MadmanMartian** [comment]
fixed by #4787
