### ISSUE TITLE
Bluespace Harpoon Teleports People into Containers

### ISSUE THREAD

**Issue by Alexshreds** [discordia-space/CEV-Eris#469]
Somehow the RD managed to become part of the contents of a space cleaner bottle.

**Comment by fluorescent-net** [comment]
Could you provide some screenshots?

**Comment by PlinHost** [comment]
>50: O.loc = pick(orange(24,user))
>59: M.loc = pick(orange(24,user))
>70: O.loc = pick(orange(24,user))
>79: M.loc = pick(orange(24,user))
orange returns a list of all atoms not only turfs

**Comment by EkuDza** [comment]
Это говно, которое я побырику перепиздил по реквеску шепки, посмотрел что спиздил и начал плакать кровью.  Надеюсь того, кто его накодил, сюда не пустят.  Этот баг известен и в иссуях есть и, кажется, на меня записан. После худа буду переписывать\фиксить.
