### ISSUE TITLE
Carpet subtypes' icons are placeholders

### ISSUE THREAD

**Issue by btwotwo** [discordia-space/CEV-Eris#477]
- /obj/item/stack/tile/carpet/bcarpet
- /obj/item/stack/tile/carpet/blucarpet
- /obj/item/stack/tile/carpet/turcarpet
- /obj/item/stack/tile/carpet/sblucarpet
- /obj/item/stack/tile/carpet/gaycarpet
- /obj/item/stack/tile/carpet/purcarpet
- /obj/item/stack/tile/carpet/oracarpet

**Comment by Euronem** [comment]
![face-with-tears-of-joy](https://cloud.githubusercontent.com/assets/17518355/22729576/647966b4-edf4-11e6-8aac-ab60522e364d.png)
