### ISSUE TITLE
No more black crit overlay

### ISSUE THREAD

**Issue by ghost** [discordia-space/CEV-Eris#489]
Is this white flour when in crit okay?
![](https://images.discordapp.net/.eJwFwVsOhCAMAMC7cABanhFvQ5CgUSmhNX6YvfvOfOqZl1rVLjJ4BdgOLjQ3zUIzt6obUbtqHgfrQjdkkVz2u3ZhsDF4Y2xA503wLrkIdkGDyS8uIib0Jjl4-tnp7Xr0pn5_BCMixw.9SwFVna_EA-uhVGuDiYdhDQw52I?width=440&height=440)

**Comment by SpadesSlick** [comment]
Done.
