### ISSUE TITLE
Local testing is broken

### ISSUE THREAD

**Issue by Kurgis** [discordia-space/CEV-Eris#4935]
#4909 has caused local hosts to runtime and then hang.

[runtime-2020-05-26.log](https://github.com/discordia-space/CEV-Eris/files/4684851/runtime-2020-05-26.log)

**Comment by Arokha** [comment]
Is that several server starts? Since I notice inventory subsystem in there 3 times

**Comment by MadmanMartian** [comment]
Dies at this point. I littered the code with debug, and it never gets past this line

![rine end here](https://cdn.discordapp.com/attachments/265411250341543936/714975053183320135/unknown.png)

**Comment by TorinoFermic** [comment]
code\modules\client\client procs.dm at line 284
