### ISSUE TITLE
If you put bedspread in the backpack, you can't take it out of it.

### ISSUE THREAD

**Issue by ZAHA046** [discordia-space/CEV-Eris#4965]
[BUG] When you try to remove the bedspread from the backpack, you fold it and rest

**Comment by ZAHA046** [comment]
When you try to remove the bedspread from the backpack, you fold it and rest

**Comment by CaptainSlumbo** [comment]
can you explain what a bedspread is I couldn't find it in the code?

**Comment by MadmanMartian** [comment]
It's probably a bedsheet

**Comment by Tea-Primoris** [comment]
Bedsheets removes from backpack without problem now, so I will close that issue.
