### ISSUE TITLE
Mob's head starts flashing after joining as observer.

### ISSUE THREAD

**Issue by fluorescent-net** [discordia-space/CEV-Eris#504]
https://i.gyazo.com/f37a6f00be862d83b923a9e2ff62b8c4.mp4
https://i.gyazo.com/e56527aa72796df121fda05acf72dad4.mp4

This doesn't happen when you become observer after playing (by ghosting, dying, etc.)

**Comment by SpadesSlick** [comment]
Это происходит от определенных причесок, похоже.

**Comment by SpadesSlick** [comment]
У меня такое тоже было, когда персонаж был лысым. Иконка для госта в таком случае вроде как берется из сетапа, нужно проверять там.

**Comment by fluorescent-net** [comment]
Вчера зашёл гостом - у него мигали рука и нога.

**Comment by LethalGhost** [comment]
Звучит как фича.

**Comment by SpadesSlick** [comment]
No longer relevant.
