### ISSUE TITLE
Spider Core generates new body without any description

### ISSUE THREAD

**Issue by MrFoxik** [discordia-space/CEV-Eris#5155]
And even doesn't takes time to create, it just spawns out of air.
Should probably consume DNA points, or have source of fresh meat to do so.
It probably should take not a minute to GIVE ABILITY to make body, but take one minute to wait for it to create around you.

**Comment by TheShown911** [comment]
Added a minute long timer to stand still and make a body, with a nice message and more gibs.
When a new body is made you lose half DNA points and half of the evolved powers.

**Comment by MrFoxik** [comment]
Fixed, would be nice to add some sounds to process, but it's okay.
