### ISSUE TITLE
runtime error: Cannot execute null.GetJob().

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#518]
runtime error: Cannot execute null.GetJob().
proc name: update preview icon (/datum/preferences/proc/update_preview_icon)
source file: preferences_setup.dm,259
usr: Valentine1488 (/mob/new_player)
src: /datum/preferences (/datum/preferences)
usr.loc: null
call stack:
/datum/preferences (/datum/preferences): update preview icon()
Body (/datum/category_item/player_setup_item/general/body): content(Valentine1488 (/mob/new_player))
General (/datum/category_group/player_setup_category/general_preferences): content(Valentine1488 (/mob/new_player))
/datum/category_collection/pla... (/datum/category_collection/player_setup_collection): content(Valentine1488 (/mob/new_player))
/datum/preferences (/datum/preferences): ShowChoices(Valentine1488 (/mob/new_player))
Valentine1488 (/mob/new_player): Topic("src=[0x300003e];show_preferen...", /list (/list))
Valentine1488 (/client): Topic("src=[0x300003e];show_preferen...", /list (/list), Valentine1488 (/mob/new_player))
Valentine1488 (/client): Topic("src=[0x300003e];show_preferen...", /list (/list), Valentine1488 (/mob/new_player))

**Comment by ACCount12** [comment]
Haven't seen this one in ages, likely fixed already. Re-open if it isn't.
