### ISSUE TITLE
Deconstructing Nanopaste doesn't use up the nanopaste, doesn't tick up research levels, and still gives you research points.

### ISSUE THREAD

**Issue by Leon9621** [discordia-space/CEV-Eris#5289]
https://i.imgur.com/G2moJG5.png With the RND machine looking like this, I'm able to repeatedly break down the nanopaste for 155 points without the gain of points ever going down or the item being used up.

**Comment by Leon9621** [comment]
To be clear, this is on a downstream, so it's possible that we've made a change that breaks this for some reason.

**Comment by Leon9621** [comment]
To be even more detailed, it was using up one charge out of the entire stack per deconstruction. Found that out later.

**Comment by SpadesSlick** [comment]
This bug was fixed months ago here, please setup something like merge bot for your downstream to don't miss our updates.
