### ISSUE TITLE
Adjust the timer of carrion infection

### ISSUE THREAD

**Issue by Jan-Blasiak** [discordia-space/CEV-Eris#5294]
Currently there is no time to save a crew member infected by carrion unless they were infected directly in medbay, next to operating table. The transformation timer is waaaaay too fast, before you manage to rush to the operating table you'll already be past the stage in which removing carrion core will kill you.

I recommend extending it to 5 minutes, with shakes beginning at 2 minute mark.

**Comment by Iglpigl** [comment]
Already fixed in #5271 
https://github.com/discordia-space/CEV-Eris/pull/5271

**Comment by Jan-Blasiak** [comment]
Thank you, didn't see that.
