### ISSUE TITLE
Chat names with cyrillics break NTOS consoles

### ISSUE THREAD

**Issue by ghost** [discordia-space/CEV-Eris#560]
/obj/machinery/modular_computer/console breaks if chat with cyrillics in it's name created in NTNet Relay Chat Client. Error messages won't go away until relogged.

![temp1](https://cloud.githubusercontent.com/assets/25551179/23014247/2bea823c-f43f-11e6-82bd-d7a447500b6f.png)

**Comment by fluorescent-net** [comment]
:javascript:

**Comment by fluorescent-net** [comment]
@bo20202

**Comment by bo20202** [comment]
😂

**Comment by Euronem** [comment]
😅😅😅😅😅😅😅😅

**Comment by bo20202** [comment]
Скинь сам файлик пожалуйста

**Comment by ACCount12** [comment]
Failed to reproduce. Was likely fixed at some point.
