### ISSUE TITLE
Supermatter cascade needs revision

### ISSUE THREAD

**Issue by MyLittleLoly** [discordia-space/CEV-Eris#583]
While fixing runtimes (#519) it appeared that this endgame event exactly needs tests, figuring out how it ever works and placing required landmarks. Currently there are endgame landmarks on escape pods and Bluespace Rift above supermatter that I've placed.

**Comment by astralenigma** [comment]
What is this supposed to be?

**Comment by SpadesSlick** [comment]
Bay12 event, with bluespace devouring everything. I don't think we even need it.
