### ISSUE TITLE
Overwatch - ability to target turfs.

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#593]
Implement  the following feauture: when you click the floor in Aim mode (the one, activated by turf) the character will point his weapon there and shoot if someone crosses the targeted tile according to these parameters:
![image](https://cloud.githubusercontent.com/assets/9161564/23555178/f30e2bfc-0038-11e7-8d94-32deb3b6bac0.png)
It means, it won't fire of someone WALKS on this tile, and it option is activate by shooyer. It is not required to indicate that cross over turf.

**Comment by ACCount12** [comment]
Aim modes are dead and gone, so this ain't happening.
