### ISSUE TITLE
Stungloves to Ironhammer specops instead of stunbatons

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#594]
![image](https://cloud.githubusercontent.com/assets/9161564/23555294/73e0611e-0039-11e7-8766-6826020592e2.png)
This should be accessory which is put up on a glove. When disarming it should play baton sound, sound of punching with fist and deal a little damage for increasing the brutality.

Required item sprite, glove overlay sprite and character overlay sprite.

**Comment by fluorescent-net** [comment]
DOOMFIST CONFIRMED

**Comment by RandomColonist** [comment]
чё блять

**Comment by SpadesSlick** [comment]
https://cdn.discordapp.com/attachments/265411250341543936/300573638107594752/stun-golves.dmi

Sprites for them.

**Comment by SpadesSlick** [comment]
Was made already.
