### ISSUE TITLE
Grab and harm characters through the shadow.

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#618]
Be able to deal damage with handheld weapons, disarm and grab character through the shadow, pulling him out from the pits. From brig, for instance. Also it is worth to add check for lying, is's not that alright to be able to reach character lying a floor below.

**Comment by Quardbreak** [comment]
Ойнет, я чёт не думаю что это хорошая идея пуллить кого-то с первого этажа на второй, это надо иметь очень длинный руки чтобы поднять человека с двух-трёх метров.

**Comment by SpadesSlick** [comment]
Ну так же за шкирку грабаешь, за плечи или голову, а не за ноги.

**Comment by Quardbreak** [comment]
Я всё же не думаю что это будет очень на балансе, вот если добавить такие вещи как гарпуны с верёвкой которые можно прикрепить к стенке, рядом с которой есть верхний свободный уровень - думаю будет логичнее.
А ещё можно прилепить шесты, например для инженеров чтобы как пожарные спускаться и не ломать себе ноги.

**Comment by LethalGhost** [comment]
Путь утаскивание наверх будет только со стола, стула, шкафчика.
