### ISSUE TITLE
Add "Null-grav" generator

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#622]
A small device for the engineers, able to disbale gravity in a radius of 5 tiles around it and 3 tiles on ablove- and below levels. It can be used instead of stepladders, when other ladders are broken as well as for other z-level related engineeering stuff.

**Comment by fluorescent-net** [comment]
GRAVITON SURGE INCOMING
FIRE AT WILL

**Comment by Quardbreak** [comment]
Oh my fucking god
When its happened?

**Comment by bo20202** [comment]
Ogon' po gotovnosti!
