### ISSUE TITLE
Bay's lags

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#626]
Bay significantly lags from time to time, it is quite obvious that the problem in controllers of all sorts of Atmos and machinery. That's just not so clear: How does the lag appear when moving a character, when Bay not so long ago adapted the controller to guarantee the smoothness of other processes, even if the rest is very heavily loaded, and we have this controller already ported?

Maybe Bay made it not fully, or we not fully ported it, but this is a very important issue. The jerking of the screen when you moving is killing half of the charm of many things, for example, parallax, and generally does not look good in 2017.

**Comment by Quardbreak** [comment]
Opened because we need new method to make game smoothest to everyone

**Comment by SpadesSlick** [comment]
Partially done.
