### ISSUE TITLE
carrion permastun after using revive stasis

### ISSUE THREAD

**Issue by kiwedespars** [discordia-space/CEV-Eris#6301]
carrions get permanently hardstunned by any stun source 10 minutes after using revive stasis

**Comment by L74814** [comment]
thanks to this I can reproduce the bug now. Now time to find the fix. This has been more helpful than all other people saying

"just trip on plating after stasis"

I can confirm that the stun happens after the first 10 minutes, in the meantime you don't get any hardstun.
