### ISSUE TITLE
Runtime in human_defense.dm,174: bad index

### ISSUE THREAD

**Issue by sl0w3st** [discordia-space/CEV-Eris#6389]
Raising shield by toggling move intent to Walk causes to nullify shield's `.armor` field

Calling `initial(armor)` return null object for some reason.

Code piece that causes it (line 119):
https://github.com/discordia-space/CEV-Eris/blob/09e5d1a1b1a47fd1a0e0e69b220efeff8d2f4f68/code/game/objects/items/weapons/shields.dm#L110-L121

Walk intent:
![walkin](https://user-images.githubusercontent.com/5019905/126068288-499b537b-664a-4f5d-8b12-e0a43189e564.png)
Run intent:
![runnin](https://user-images.githubusercontent.com/5019905/126068406-04c3411f-4d26-4a72-8c24-57b75b35ffb5.png)

**Comment by MadmanMartian** [comment]
You can't call initial on a list, it just returns null.
