### ISSUE TITLE
Moebius Plaques do not show up

### ISSUE THREAD

**Issue by ValoTheValo** [discordia-space/CEV-Eris#6903]
the moebius plaques in med bay lobby and R&D lockers don't actually appear on the server. despite being mapped in

**Comment by greenteaguzzler** [comment]
Applies to all floor decals
![image](https://user-images.githubusercontent.com/95113773/147303504-606864f2-9f25-4def-8f47-5dd8d0ab7613.png)
![image](https://user-images.githubusercontent.com/95113773/147303522-488a0ff6-9867-4463-828c-33c5353b868a.png)

**Comment by Kurgis** [comment]
This appears to only affect floor decals on round-start, applying floor decals works normally _until_ update_neighbors is called, where they will then disappear again. So these decals are being applied, and then when the proc to update neighboring tiles goes off they just vanish.

For reference:
https://github.com/discordia-space/CEV-Eris/blob/master/code/game/turfs/simulated/floor_icon.dm
https://github.com/AlexMorgan3817/CEV-Eris/blob/master/code/game/turfs/flooring/flooring_decals.dm
