### ISSUE TITLE
Placing chemical bottles onto tables will place them in the middle of the table

### ISSUE THREAD

**Issue by mattroks101** [discordia-space/CEV-Eris#734]
Some preset reagent containers on the map also don't adhere to x and y pixel placement on tables. Like the beers in the bar.

**Comment by LethalGhost** [comment]
Seem like conflicts between new "place everything with click" and old "only chem-containers related" systems.
I think we need rewrite it completely. May be copy-past TG code.

**Comment by LagannPM** [comment]
i suppose it fixed
