### ISSUE TITLE
Text to speech not working in local build

### ISSUE THREAD

**Issue by ModDownloading** [discordia-space/CEV-Eris#7378]
Eris Station's text to speech platform doesn't seem to work if you download and compile the source code and try to use the system locally on a private testing server. I have made sure I uncommented the TTS_ENABLED and TTS_CACHE settings in the config folder and ensured they were set to true and that they were not in the example subfolder (since config settings don't work if they're still in there). For some reason, even after all of this the service doesn't work locally, which I find to be an issue because it means I can't test out what works and what doesn't work with the text to speech system unless I go onto the actual server, and that is something I can't do on weekdays, and can't do completely freely (I shouldn't say out-of-context stuff on a roleplay server, for instance).

Am I missing something else that I need to change in the config folder or somewhere else to allow me to test all the text to speech voices locally? I would greatly appreciate any help to getting this system working since it's a really neat feature.

**Comment by MLGTASTICa** [comment]
You need to have a link to the NovelAI website with your own subscription to it.

**Comment by ModDownloading** [comment]
Well drat, I was hoping the system was integrated into Eris Station code. I don't know if I need text to speech that badly that I'd get a subscription for it, but at least I can enjoy it on the server when it's up. Thanks.
