### ISSUE TITLE
Voice Changer mask doesn't seem to work

### ISSUE THREAD

**Issue by Sharmount** [discordia-space/CEV-Eris#742]
While someone had another ID and the mask was enabled, it did nothing.

**Comment by MrFoxik** [comment]
Fixed

> You enable the voice-changing module in the gas mask.
> Jaiden Chapman(as Unknown) says, "Gay"
> Jaiden Chapman says, "Gay"
> You are now mimicking Harry Potter.
> Harry Potter(as Unknown) says, "Haha"
