### ISSUE TITLE
Prescription glasses and sunglasses do not work.

### ISSUE THREAD

**Issue by 5crownik007** [discordia-space/CEV-Eris#764]
See title.
Having a character who requires glasses to see will result in your screen being covered in black dots.
Even with the required glasses, your character will be blinded permanently. valve pls fix

**Comment by Sharmount** [comment]
![ea4a1b031331001b8900f83bb6c49586](https://cloud.githubusercontent.com/assets/20283678/25123575/13d18576-2453-11e7-9beb-29658af78bad.png)

**Comment by SpadesSlick** [comment]
Fixed.
