### ISSUE TITLE
Shotgun magazines sprites invisible, both as items and when in the gun

### ISSUE THREAD

**Issue by maikilangiolo** [discordia-space/CEV-Eris#8236]
- the short shotgun magazine is invisible, empty and when filled with ammo. only the two-pixel wide bullet overlay shows
- both the short mag and the drum are invisible when loaded into the gun, so the gun shows as not loaded
![image](https://github.com/discordia-space/CEV-Eris/assets/40152611/aea78b8c-0403-4c0f-a9ed-545047483106)
here you can see a shotgun currently loaded with a drum, and the bullet overlay on the shot magazine.

must have been broken by a recent PR because in #8193 I provided screenshots of the PR having been tested, and the AK shows as being loaded correctly.

**Comment by Evie7056** [comment]
https://discord.com/channels/255035529085583360/375588651599396866/1123693295030259755

Thats kinda at least several launch

**Comment by SirRichardFrancis** [comment]
Appears to be fixed since.
