### ISSUE TITLE
Рекодинг светомашинерии

### ISSUE THREAD

**Issue by EkuDza** [discordia-space/CEV-Eris#84]
Это добавлено чтобы не забыть. На момент написания это не критично и можно игнорировать.

Код постройки света немного убог, особенно после того как добавили наполный свет.

Нужно будет проанализировать lighting.dm
Файлы которые имеют отношение и возможно нужно будет дополнительно проанализировать и провести рекодинг:
wall_frames, wall_attack, floor_attackby, unsorted

**Comment by ModernViolence** [comment]
Наверное, таска станет неактуальной после #237

**Comment by SpadesSlick** [comment]
No longer actual.
