### ISSUE TITLE
Sprites for IHS rig are wrong

### ISSUE THREAD

**Issue by SpadesSlick** [discordia-space/CEV-Eris#849]
![image](https://user-images.githubusercontent.com/9161564/27508952-8f1fabc4-58f9-11e7-9cda-452c5b5cecbc.png)
You can see one pixel of skin here. Same for boots.
![image](https://user-images.githubusercontent.com/9161564/27508995-e074312e-58fa-11e7-8e68-969cb7b4485c.png)
And light just works wrong.

**Comment by Garen7** [comment]
The IHS rig sprite was changed, this can be closed
