### ISSUE TITLE
Need to fix GUI

### ISSUE THREAD

**Issue by Broda1** [discordia-space/CEV-Eris#858]
![image](https://user-images.githubusercontent.com/5676099/27518198-836096e0-59f3-11e7-9900-3bd3f7759b64.png)

**Comment by LethalGhost** [comment]
https://github.com/Endless-Horizon/CEV-Eris/blob/master/code/game/objects/items/weapons/storage/storage.dm
Lines 551, 558, 564, 570 declare position of boxes on the hud.
Example:
`src.storage_start.screen_loc = "7,7 to 10,8"`

**Comment by fluorescent-net** [comment]
![image](https://image.prntscr.com/image/5ZQ6LeZAQ9_dZDgc2vJGOw.png)
Well, don't think that was finally fixed.
