### ISSUE TITLE
Ventilation can not pump out

### ISSUE THREAD

**Issue by TermService** [discordia-space/CEV-Eris#925]
Ventilation is pumped through the ass. Very quickly pumps up the atmosphere and takes a long time to pump out + for ventilation there are no icons for pumping out and inflating the atmosphere
![yj_lzlyqrpgvkh4494a99g](https://user-images.githubusercontent.com/18397924/28494147-cfd3b2d2-6f2e-11e7-91c7-ff3b020e2406.png)

**Comment by ACCount12** [comment]
Should be fixed by #4310, if not earlier.
