### ISSUE TITLE
Characters on ID card photo has no clothings at all

### ISSUE THREAD

**Issue by LethalGhost** [discordia-space/CEV-Eris#959]
![1717](https://user-images.githubusercontent.com/2458675/28997584-ba93e2ee-7a31-11e7-9bdc-2590037305a3.png)

**Comment by MrFoxik** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/21274357/57014423-bac50600-6c18-11e9-869e-cad144be4c6e.png)
