### ISSUE TITLE
Computer disassembly

### ISSUE THREAD

**Issue by TermService** [discordia-space/CEV-Eris#973]
Eng: We use a screwdriver on any computer (with the exception of consoles) and instead of parsing we get a computer frame, it can be screwed with a wrench, but you can not get the board and accessories.
_________________________________________________________________________________________________________________
Ru: Используйте отвертку на любом компьютере, получим компьютер фрейм вместо разбора, ничего достать нельзя, отличный способ погрифонить. (на консоли не распространяется, хотя они тоже через жопу работают).

![screenshot_1](https://user-images.githubusercontent.com/18397924/29303402-35bbd3ae-8195-11e7-94eb-accca0c93012.png)

**Comment by MrFoxik** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/21274357/57014532-2e671300-6c19-11e9-8d42-9d2098e79075.png)
